// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.5
// source: proto/beam/beam_node.proto

package beam

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BeamNodeService_Authenticate_FullMethodName      = "/dylaris.beam.BeamNodeService/Authenticate"
	BeamNodeService_ListFiles_FullMethodName         = "/dylaris.beam.BeamNodeService/ListFiles"
	BeamNodeService_ReadFileContent_FullMethodName   = "/dylaris.beam.BeamNodeService/ReadFileContent"
	BeamNodeService_SaveFileContent_FullMethodName   = "/dylaris.beam.BeamNodeService/SaveFileContent"
	BeamNodeService_CreateFile_FullMethodName        = "/dylaris.beam.BeamNodeService/CreateFile"
	BeamNodeService_DeleteFile_FullMethodName        = "/dylaris.beam.BeamNodeService/DeleteFile"
	BeamNodeService_RenameFile_FullMethodName        = "/dylaris.beam.BeamNodeService/RenameFile"
	BeamNodeService_CopyFile_FullMethodName          = "/dylaris.beam.BeamNodeService/CopyFile"
	BeamNodeService_DownloadFile_FullMethodName      = "/dylaris.beam.BeamNodeService/DownloadFile"
	BeamNodeService_UploadFile_FullMethodName        = "/dylaris.beam.BeamNodeService/UploadFile"
	BeamNodeService_DownloadSelective_FullMethodName = "/dylaris.beam.BeamNodeService/DownloadSelective"
	BeamNodeService_GetTransferQuota_FullMethodName  = "/dylaris.beam.BeamNodeService/GetTransferQuota"
)

// BeamNodeServiceClient is the client API for BeamNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BeamNodeService runs on each Node (localhost:9091 only).
// Beam desktop clients connect through the BeamRelay tunnel.
// Auth is stateless: Node validates the JWT ticket signature locally.
type BeamNodeServiceClient interface {
	// Auth: first call after gRPC channel opens. Validates the signed ticket.
	Authenticate(ctx context.Context, in *BeamAuthReq, opts ...grpc.CallOption) (*BeamAuthResp, error)
	// File operations
	ListFiles(ctx context.Context, in *BeamFileListReq, opts ...grpc.CallOption) (*BeamFileListResp, error)
	ReadFileContent(ctx context.Context, in *BeamFileReadReq, opts ...grpc.CallOption) (*BeamFileContentResp, error)
	SaveFileContent(ctx context.Context, in *BeamFileSaveReq, opts ...grpc.CallOption) (*BeamOpResp, error)
	CreateFile(ctx context.Context, in *BeamFileCreateReq, opts ...grpc.CallOption) (*BeamOpResp, error)
	DeleteFile(ctx context.Context, in *BeamFileDeleteReq, opts ...grpc.CallOption) (*BeamOpResp, error)
	RenameFile(ctx context.Context, in *BeamFileRenameReq, opts ...grpc.CallOption) (*BeamOpResp, error)
	CopyFile(ctx context.Context, in *BeamFileCopyReq, opts ...grpc.CallOption) (*BeamOpResp, error)
	// Streaming transfers (64KB chunks)
	DownloadFile(ctx context.Context, in *BeamDownloadReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BeamChunk], error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BeamUploadMsg, BeamOpResp], error)
	DownloadSelective(ctx context.Context, in *BeamSelectiveReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BeamChunk], error)
	// Transfer quota info
	GetTransferQuota(ctx context.Context, in *BeamQuotaReq, opts ...grpc.CallOption) (*BeamQuotaResp, error)
}

type beamNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBeamNodeServiceClient(cc grpc.ClientConnInterface) BeamNodeServiceClient {
	return &beamNodeServiceClient{cc}
}

func (c *beamNodeServiceClient) Authenticate(ctx context.Context, in *BeamAuthReq, opts ...grpc.CallOption) (*BeamAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamAuthResp)
	err := c.cc.Invoke(ctx, BeamNodeService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) ListFiles(ctx context.Context, in *BeamFileListReq, opts ...grpc.CallOption) (*BeamFileListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamFileListResp)
	err := c.cc.Invoke(ctx, BeamNodeService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) ReadFileContent(ctx context.Context, in *BeamFileReadReq, opts ...grpc.CallOption) (*BeamFileContentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamFileContentResp)
	err := c.cc.Invoke(ctx, BeamNodeService_ReadFileContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) SaveFileContent(ctx context.Context, in *BeamFileSaveReq, opts ...grpc.CallOption) (*BeamOpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamOpResp)
	err := c.cc.Invoke(ctx, BeamNodeService_SaveFileContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) CreateFile(ctx context.Context, in *BeamFileCreateReq, opts ...grpc.CallOption) (*BeamOpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamOpResp)
	err := c.cc.Invoke(ctx, BeamNodeService_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) DeleteFile(ctx context.Context, in *BeamFileDeleteReq, opts ...grpc.CallOption) (*BeamOpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamOpResp)
	err := c.cc.Invoke(ctx, BeamNodeService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) RenameFile(ctx context.Context, in *BeamFileRenameReq, opts ...grpc.CallOption) (*BeamOpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamOpResp)
	err := c.cc.Invoke(ctx, BeamNodeService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) CopyFile(ctx context.Context, in *BeamFileCopyReq, opts ...grpc.CallOption) (*BeamOpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamOpResp)
	err := c.cc.Invoke(ctx, BeamNodeService_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beamNodeServiceClient) DownloadFile(ctx context.Context, in *BeamDownloadReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BeamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BeamNodeService_ServiceDesc.Streams[0], BeamNodeService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BeamDownloadReq, BeamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeamNodeService_DownloadFileClient = grpc.ServerStreamingClient[BeamChunk]

func (c *beamNodeServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BeamUploadMsg, BeamOpResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BeamNodeService_ServiceDesc.Streams[1], BeamNodeService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BeamUploadMsg, BeamOpResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeamNodeService_UploadFileClient = grpc.ClientStreamingClient[BeamUploadMsg, BeamOpResp]

func (c *beamNodeServiceClient) DownloadSelective(ctx context.Context, in *BeamSelectiveReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BeamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BeamNodeService_ServiceDesc.Streams[2], BeamNodeService_DownloadSelective_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BeamSelectiveReq, BeamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeamNodeService_DownloadSelectiveClient = grpc.ServerStreamingClient[BeamChunk]

func (c *beamNodeServiceClient) GetTransferQuota(ctx context.Context, in *BeamQuotaReq, opts ...grpc.CallOption) (*BeamQuotaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeamQuotaResp)
	err := c.cc.Invoke(ctx, BeamNodeService_GetTransferQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeamNodeServiceServer is the server API for BeamNodeService service.
// All implementations must embed UnimplementedBeamNodeServiceServer
// for forward compatibility.
//
// BeamNodeService runs on each Node (localhost:9091 only).
// Beam desktop clients connect through the BeamRelay tunnel.
// Auth is stateless: Node validates the JWT ticket signature locally.
type BeamNodeServiceServer interface {
	// Auth: first call after gRPC channel opens. Validates the signed ticket.
	Authenticate(context.Context, *BeamAuthReq) (*BeamAuthResp, error)
	// File operations
	ListFiles(context.Context, *BeamFileListReq) (*BeamFileListResp, error)
	ReadFileContent(context.Context, *BeamFileReadReq) (*BeamFileContentResp, error)
	SaveFileContent(context.Context, *BeamFileSaveReq) (*BeamOpResp, error)
	CreateFile(context.Context, *BeamFileCreateReq) (*BeamOpResp, error)
	DeleteFile(context.Context, *BeamFileDeleteReq) (*BeamOpResp, error)
	RenameFile(context.Context, *BeamFileRenameReq) (*BeamOpResp, error)
	CopyFile(context.Context, *BeamFileCopyReq) (*BeamOpResp, error)
	// Streaming transfers (64KB chunks)
	DownloadFile(*BeamDownloadReq, grpc.ServerStreamingServer[BeamChunk]) error
	UploadFile(grpc.ClientStreamingServer[BeamUploadMsg, BeamOpResp]) error
	DownloadSelective(*BeamSelectiveReq, grpc.ServerStreamingServer[BeamChunk]) error
	// Transfer quota info
	GetTransferQuota(context.Context, *BeamQuotaReq) (*BeamQuotaResp, error)
	mustEmbedUnimplementedBeamNodeServiceServer()
}

// UnimplementedBeamNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBeamNodeServiceServer struct{}

func (UnimplementedBeamNodeServiceServer) Authenticate(context.Context, *BeamAuthReq) (*BeamAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedBeamNodeServiceServer) ListFiles(context.Context, *BeamFileListReq) (*BeamFileListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedBeamNodeServiceServer) ReadFileContent(context.Context, *BeamFileReadReq) (*BeamFileContentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFileContent not implemented")
}
func (UnimplementedBeamNodeServiceServer) SaveFileContent(context.Context, *BeamFileSaveReq) (*BeamOpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveFileContent not implemented")
}
func (UnimplementedBeamNodeServiceServer) CreateFile(context.Context, *BeamFileCreateReq) (*BeamOpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedBeamNodeServiceServer) DeleteFile(context.Context, *BeamFileDeleteReq) (*BeamOpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedBeamNodeServiceServer) RenameFile(context.Context, *BeamFileRenameReq) (*BeamOpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedBeamNodeServiceServer) CopyFile(context.Context, *BeamFileCopyReq) (*BeamOpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedBeamNodeServiceServer) DownloadFile(*BeamDownloadReq, grpc.ServerStreamingServer[BeamChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedBeamNodeServiceServer) UploadFile(grpc.ClientStreamingServer[BeamUploadMsg, BeamOpResp]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedBeamNodeServiceServer) DownloadSelective(*BeamSelectiveReq, grpc.ServerStreamingServer[BeamChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadSelective not implemented")
}
func (UnimplementedBeamNodeServiceServer) GetTransferQuota(context.Context, *BeamQuotaReq) (*BeamQuotaResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferQuota not implemented")
}
func (UnimplementedBeamNodeServiceServer) mustEmbedUnimplementedBeamNodeServiceServer() {}
func (UnimplementedBeamNodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeBeamNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeamNodeServiceServer will
// result in compilation errors.
type UnsafeBeamNodeServiceServer interface {
	mustEmbedUnimplementedBeamNodeServiceServer()
}

func RegisterBeamNodeServiceServer(s grpc.ServiceRegistrar, srv BeamNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedBeamNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BeamNodeService_ServiceDesc, srv)
}

func _BeamNodeService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).Authenticate(ctx, req.(*BeamAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamFileListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).ListFiles(ctx, req.(*BeamFileListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_ReadFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamFileReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).ReadFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_ReadFileContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).ReadFileContent(ctx, req.(*BeamFileReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_SaveFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamFileSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).SaveFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_SaveFileContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).SaveFileContent(ctx, req.(*BeamFileSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamFileCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).CreateFile(ctx, req.(*BeamFileCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamFileDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).DeleteFile(ctx, req.(*BeamFileDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamFileRenameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).RenameFile(ctx, req.(*BeamFileRenameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamFileCopyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).CopyFile(ctx, req.(*BeamFileCopyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeamNodeService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BeamDownloadReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeamNodeServiceServer).DownloadFile(m, &grpc.GenericServerStream[BeamDownloadReq, BeamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeamNodeService_DownloadFileServer = grpc.ServerStreamingServer[BeamChunk]

func _BeamNodeService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BeamNodeServiceServer).UploadFile(&grpc.GenericServerStream[BeamUploadMsg, BeamOpResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeamNodeService_UploadFileServer = grpc.ClientStreamingServer[BeamUploadMsg, BeamOpResp]

func _BeamNodeService_DownloadSelective_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BeamSelectiveReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeamNodeServiceServer).DownloadSelective(m, &grpc.GenericServerStream[BeamSelectiveReq, BeamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeamNodeService_DownloadSelectiveServer = grpc.ServerStreamingServer[BeamChunk]

func _BeamNodeService_GetTransferQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeamQuotaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeamNodeServiceServer).GetTransferQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeamNodeService_GetTransferQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeamNodeServiceServer).GetTransferQuota(ctx, req.(*BeamQuotaReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BeamNodeService_ServiceDesc is the grpc.ServiceDesc for BeamNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeamNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dylaris.beam.BeamNodeService",
	HandlerType: (*BeamNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _BeamNodeService_Authenticate_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _BeamNodeService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFileContent",
			Handler:    _BeamNodeService_ReadFileContent_Handler,
		},
		{
			MethodName: "SaveFileContent",
			Handler:    _BeamNodeService_SaveFileContent_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _BeamNodeService_CreateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _BeamNodeService_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _BeamNodeService_RenameFile_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _BeamNodeService_CopyFile_Handler,
		},
		{
			MethodName: "GetTransferQuota",
			Handler:    _BeamNodeService_GetTransferQuota_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _BeamNodeService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _BeamNodeService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadSelective",
			Handler:       _BeamNodeService_DownloadSelective_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/beam/beam_node.proto",
}
