// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: proto/beam/beam_node.proto

package beam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeamAuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"` // JWT signed by Core (contains server_uuid, username, permissions, node_id, expires)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamAuthReq) Reset() {
	*x = BeamAuthReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamAuthReq) ProtoMessage() {}

func (x *BeamAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamAuthReq.ProtoReflect.Descriptor instead.
func (*BeamAuthReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{0}
}

func (x *BeamAuthReq) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type BeamAuthResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerUuid      string                 `protobuf:"bytes,3,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	IsAdmin         bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	SubServers      []string               `protobuf:"bytes,6,rep,name=sub_servers,json=subServers,proto3" json:"sub_servers,omitempty"`                  // Available sub-servers for this server
	ActiveSubServer string                 `protobuf:"bytes,7,opt,name=active_sub_server,json=activeSubServer,proto3" json:"active_sub_server,omitempty"` // Currently active sub-server
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BeamAuthResp) Reset() {
	*x = BeamAuthResp{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamAuthResp) ProtoMessage() {}

func (x *BeamAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamAuthResp.ProtoReflect.Descriptor instead.
func (*BeamAuthResp) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{1}
}

func (x *BeamAuthResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BeamAuthResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BeamAuthResp) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *BeamAuthResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BeamAuthResp) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *BeamAuthResp) GetSubServers() []string {
	if x != nil {
		return x.SubServers
	}
	return nil
}

func (x *BeamAuthResp) GetActiveSubServer() string {
	if x != nil {
		return x.ActiveSubServer
	}
	return ""
}

type BeamFileListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Relative to server root (e.g. "" or "plugins/")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileListReq) Reset() {
	*x = BeamFileListReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileListReq) ProtoMessage() {}

func (x *BeamFileListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileListReq.ProtoReflect.Descriptor instead.
func (*BeamFileListReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{2}
}

func (x *BeamFileListReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BeamFileListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*BeamFileInfo        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileListResp) Reset() {
	*x = BeamFileListResp{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileListResp) ProtoMessage() {}

func (x *BeamFileListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileListResp.ProtoReflect.Descriptor instead.
func (*BeamFileListResp) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{3}
}

func (x *BeamFileListResp) GetFiles() []*BeamFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type BeamFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Modified      int64                  `protobuf:"varint,4,opt,name=modified,proto3" json:"modified,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileInfo) Reset() {
	*x = BeamFileInfo{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileInfo) ProtoMessage() {}

func (x *BeamFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileInfo.ProtoReflect.Descriptor instead.
func (*BeamFileInfo) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{4}
}

func (x *BeamFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeamFileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *BeamFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BeamFileInfo) GetModified() int64 {
	if x != nil {
		return x.Modified
	}
	return 0
}

type BeamFileReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Relative path to text file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileReadReq) Reset() {
	*x = BeamFileReadReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileReadReq) ProtoMessage() {}

func (x *BeamFileReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileReadReq.ProtoReflect.Descriptor instead.
func (*BeamFileReadReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{5}
}

func (x *BeamFileReadReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BeamFileContentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Error message if not success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileContentResp) Reset() {
	*x = BeamFileContentResp{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileContentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileContentResp) ProtoMessage() {}

func (x *BeamFileContentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileContentResp.ProtoReflect.Descriptor instead.
func (*BeamFileContentResp) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{6}
}

func (x *BeamFileContentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BeamFileContentResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BeamFileContentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BeamFileSaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileSaveReq) Reset() {
	*x = BeamFileSaveReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileSaveReq) ProtoMessage() {}

func (x *BeamFileSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileSaveReq.ProtoReflect.Descriptor instead.
func (*BeamFileSaveReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{7}
}

func (x *BeamFileSaveReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BeamFileSaveReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type BeamFileCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileCreateReq) Reset() {
	*x = BeamFileCreateReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileCreateReq) ProtoMessage() {}

func (x *BeamFileCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileCreateReq.ProtoReflect.Descriptor instead.
func (*BeamFileCreateReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{8}
}

func (x *BeamFileCreateReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BeamFileCreateReq) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type BeamFileDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileDeleteReq) Reset() {
	*x = BeamFileDeleteReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileDeleteReq) ProtoMessage() {}

func (x *BeamFileDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileDeleteReq.ProtoReflect.Descriptor instead.
func (*BeamFileDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{9}
}

func (x *BeamFileDeleteReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BeamFileRenameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileRenameReq) Reset() {
	*x = BeamFileRenameReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileRenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileRenameReq) ProtoMessage() {}

func (x *BeamFileRenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileRenameReq.ProtoReflect.Descriptor instead.
func (*BeamFileRenameReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{10}
}

func (x *BeamFileRenameReq) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *BeamFileRenameReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type BeamFileCopyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPath       string                 `protobuf:"bytes,1,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	DstPath       string                 `protobuf:"bytes,2,opt,name=dst_path,json=dstPath,proto3" json:"dst_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamFileCopyReq) Reset() {
	*x = BeamFileCopyReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamFileCopyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamFileCopyReq) ProtoMessage() {}

func (x *BeamFileCopyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamFileCopyReq.ProtoReflect.Descriptor instead.
func (*BeamFileCopyReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{11}
}

func (x *BeamFileCopyReq) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *BeamFileCopyReq) GetDstPath() string {
	if x != nil {
		return x.DstPath
	}
	return ""
}

type BeamDownloadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ZipIfDir      bool                   `protobuf:"varint,2,opt,name=zip_if_dir,json=zipIfDir,proto3" json:"zip_if_dir,omitempty"` // If path is a directory, zip it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamDownloadReq) Reset() {
	*x = BeamDownloadReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamDownloadReq) ProtoMessage() {}

func (x *BeamDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamDownloadReq.ProtoReflect.Descriptor instead.
func (*BeamDownloadReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{12}
}

func (x *BeamDownloadReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BeamDownloadReq) GetZipIfDir() bool {
	if x != nil {
		return x.ZipIfDir
	}
	return false
}

type BeamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Max 64KB per chunk
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                     // Set on first chunk for downloads
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // Set on first chunk for progress tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamChunk) Reset() {
	*x = BeamChunk{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamChunk) ProtoMessage() {}

func (x *BeamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamChunk.ProtoReflect.Descriptor instead.
func (*BeamChunk) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{13}
}

func (x *BeamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BeamChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BeamChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BeamChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type BeamUploadMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BeamUploadMsg_Start
	//	*BeamUploadMsg_Chunk
	Payload       isBeamUploadMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamUploadMsg) Reset() {
	*x = BeamUploadMsg{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamUploadMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamUploadMsg) ProtoMessage() {}

func (x *BeamUploadMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamUploadMsg.ProtoReflect.Descriptor instead.
func (*BeamUploadMsg) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{14}
}

func (x *BeamUploadMsg) GetPayload() isBeamUploadMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BeamUploadMsg) GetStart() *BeamUploadStart {
	if x != nil {
		if x, ok := x.Payload.(*BeamUploadMsg_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *BeamUploadMsg) GetChunk() *BeamUploadChunkData {
	if x != nil {
		if x, ok := x.Payload.(*BeamUploadMsg_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isBeamUploadMsg_Payload interface {
	isBeamUploadMsg_Payload()
}

type BeamUploadMsg_Start struct {
	Start *BeamUploadStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type BeamUploadMsg_Chunk struct {
	Chunk *BeamUploadChunkData `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*BeamUploadMsg_Start) isBeamUploadMsg_Payload() {}

func (*BeamUploadMsg_Chunk) isBeamUploadMsg_Payload() {}

type BeamUploadStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`         // Remote path (directory)
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // Filename
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Strategy      string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"` // "replace", "merge"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamUploadStart) Reset() {
	*x = BeamUploadStart{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamUploadStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamUploadStart) ProtoMessage() {}

func (x *BeamUploadStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamUploadStart.ProtoReflect.Descriptor instead.
func (*BeamUploadStart) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{15}
}

func (x *BeamUploadStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BeamUploadStart) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BeamUploadStart) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *BeamUploadStart) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type BeamUploadChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamUploadChunkData) Reset() {
	*x = BeamUploadChunkData{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamUploadChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamUploadChunkData) ProtoMessage() {}

func (x *BeamUploadChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamUploadChunkData.ProtoReflect.Descriptor instead.
func (*BeamUploadChunkData) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{16}
}

func (x *BeamUploadChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BeamUploadChunkData) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type BeamSelectiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasePath      string                 `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`     // e.g. "" (server root) or "plugins/"
	Selected      []string               `protobuf:"bytes,2,rep,name=selected,proto3" json:"selected,omitempty"`                     // e.g. ["WorldEdit/", "config.yml"]
	SelectAll     bool                   `protobuf:"varint,3,opt,name=select_all,json=selectAll,proto3" json:"select_all,omitempty"` // Zip everything under base_path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamSelectiveReq) Reset() {
	*x = BeamSelectiveReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamSelectiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamSelectiveReq) ProtoMessage() {}

func (x *BeamSelectiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamSelectiveReq.ProtoReflect.Descriptor instead.
func (*BeamSelectiveReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{17}
}

func (x *BeamSelectiveReq) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *BeamSelectiveReq) GetSelected() []string {
	if x != nil {
		return x.Selected
	}
	return nil
}

func (x *BeamSelectiveReq) GetSelectAll() bool {
	if x != nil {
		return x.SelectAll
	}
	return false
}

type BeamQuotaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamQuotaReq) Reset() {
	*x = BeamQuotaReq{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamQuotaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamQuotaReq) ProtoMessage() {}

func (x *BeamQuotaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamQuotaReq.ProtoReflect.Descriptor instead.
func (*BeamQuotaReq) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{18}
}

type BeamQuotaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyUsed     int64                  `protobuf:"varint,1,opt,name=daily_used,json=dailyUsed,proto3" json:"daily_used,omitempty"`    // Bytes transferred today
	DailyLimit    int64                  `protobuf:"varint,2,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"` // 0 = unlimited
	BwLimit       int64                  `protobuf:"varint,3,opt,name=bw_limit,json=bwLimit,proto3" json:"bw_limit,omitempty"`          // Bytes/sec, 0 = unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamQuotaResp) Reset() {
	*x = BeamQuotaResp{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamQuotaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamQuotaResp) ProtoMessage() {}

func (x *BeamQuotaResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamQuotaResp.ProtoReflect.Descriptor instead.
func (*BeamQuotaResp) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{19}
}

func (x *BeamQuotaResp) GetDailyUsed() int64 {
	if x != nil {
		return x.DailyUsed
	}
	return 0
}

func (x *BeamQuotaResp) GetDailyLimit() int64 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *BeamQuotaResp) GetBwLimit() int64 {
	if x != nil {
		return x.BwLimit
	}
	return 0
}

type BeamOpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamOpResp) Reset() {
	*x = BeamOpResp{}
	mi := &file_proto_beam_beam_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamOpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamOpResp) ProtoMessage() {}

func (x *BeamOpResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beam_beam_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamOpResp.ProtoReflect.Descriptor instead.
func (*BeamOpResp) Descriptor() ([]byte, []int) {
	return file_proto_beam_beam_node_proto_rawDescGZIP(), []int{20}
}

func (x *BeamOpResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BeamOpResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_beam_beam_node_proto protoreflect.FileDescriptor

const file_proto_beam_beam_node_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/beam/beam_node.proto\x12\fdylaris.beam\"%\n" +
	"\vBeamAuthReq\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\"\xdd\x01\n" +
	"\fBeamAuthResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vserver_uuid\x18\x03 \x01(\tR\n" +
	"serverUuid\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\x12\x1f\n" +
	"\vsub_servers\x18\x06 \x03(\tR\n" +
	"subServers\x12*\n" +
	"\x11active_sub_server\x18\a \x01(\tR\x0factiveSubServer\"%\n" +
	"\x0fBeamFileListReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"D\n" +
	"\x10BeamFileListResp\x120\n" +
	"\x05files\x18\x01 \x03(\v2\x1a.dylaris.beam.BeamFileInfoR\x05files\"i\n" +
	"\fBeamFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1a\n" +
	"\bmodified\x18\x04 \x01(\x03R\bmodified\"%\n" +
	"\x0fBeamFileReadReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"c\n" +
	"\x13BeamFileContentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"?\n" +
	"\x0fBeamFileSaveReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\">\n" +
	"\x11BeamFileCreateReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\"'\n" +
	"\x11BeamFileDeleteReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"I\n" +
	"\x11BeamFileRenameReq\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"G\n" +
	"\x0fBeamFileCopyReq\x12\x19\n" +
	"\bsrc_path\x18\x01 \x01(\tR\asrcPath\x12\x19\n" +
	"\bdst_path\x18\x02 \x01(\tR\adstPath\"C\n" +
	"\x0fBeamDownloadReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\n" +
	"zip_if_dir\x18\x02 \x01(\bR\bzipIfDir\"r\n" +
	"\tBeamChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"\x8c\x01\n" +
	"\rBeamUploadMsg\x125\n" +
	"\x05start\x18\x01 \x01(\v2\x1d.dylaris.beam.BeamUploadStartH\x00R\x05start\x129\n" +
	"\x05chunk\x18\x02 \x01(\v2!.dylaris.beam.BeamUploadChunkDataH\x00R\x05chunkB\t\n" +
	"\apayload\"|\n" +
	"\x0fBeamUploadStart\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\"A\n" +
	"\x13BeamUploadChunkData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"j\n" +
	"\x10BeamSelectiveReq\x12\x1b\n" +
	"\tbase_path\x18\x01 \x01(\tR\bbasePath\x12\x1a\n" +
	"\bselected\x18\x02 \x03(\tR\bselected\x12\x1d\n" +
	"\n" +
	"select_all\x18\x03 \x01(\bR\tselectAll\"\x0e\n" +
	"\fBeamQuotaReq\"j\n" +
	"\rBeamQuotaResp\x12\x1d\n" +
	"\n" +
	"daily_used\x18\x01 \x01(\x03R\tdailyUsed\x12\x1f\n" +
	"\vdaily_limit\x18\x02 \x01(\x03R\n" +
	"dailyLimit\x12\x19\n" +
	"\bbw_limit\x18\x03 \x01(\x03R\abwLimit\"@\n" +
	"\n" +
	"BeamOpResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x93\a\n" +
	"\x0fBeamNodeService\x12E\n" +
	"\fAuthenticate\x12\x19.dylaris.beam.BeamAuthReq\x1a\x1a.dylaris.beam.BeamAuthResp\x12J\n" +
	"\tListFiles\x12\x1d.dylaris.beam.BeamFileListReq\x1a\x1e.dylaris.beam.BeamFileListResp\x12S\n" +
	"\x0fReadFileContent\x12\x1d.dylaris.beam.BeamFileReadReq\x1a!.dylaris.beam.BeamFileContentResp\x12J\n" +
	"\x0fSaveFileContent\x12\x1d.dylaris.beam.BeamFileSaveReq\x1a\x18.dylaris.beam.BeamOpResp\x12G\n" +
	"\n" +
	"CreateFile\x12\x1f.dylaris.beam.BeamFileCreateReq\x1a\x18.dylaris.beam.BeamOpResp\x12G\n" +
	"\n" +
	"DeleteFile\x12\x1f.dylaris.beam.BeamFileDeleteReq\x1a\x18.dylaris.beam.BeamOpResp\x12G\n" +
	"\n" +
	"RenameFile\x12\x1f.dylaris.beam.BeamFileRenameReq\x1a\x18.dylaris.beam.BeamOpResp\x12C\n" +
	"\bCopyFile\x12\x1d.dylaris.beam.BeamFileCopyReq\x1a\x18.dylaris.beam.BeamOpResp\x12H\n" +
	"\fDownloadFile\x12\x1d.dylaris.beam.BeamDownloadReq\x1a\x17.dylaris.beam.BeamChunk0\x01\x12E\n" +
	"\n" +
	"UploadFile\x12\x1b.dylaris.beam.BeamUploadMsg\x1a\x18.dylaris.beam.BeamOpResp(\x01\x12N\n" +
	"\x11DownloadSelective\x12\x1e.dylaris.beam.BeamSelectiveReq\x1a\x17.dylaris.beam.BeamChunk0\x01\x12K\n" +
	"\x10GetTransferQuota\x12\x1a.dylaris.beam.BeamQuotaReq\x1a\x1b.dylaris.beam.BeamQuotaRespB\x14Z\x12dylaris-proto/beamb\x06proto3"

var (
	file_proto_beam_beam_node_proto_rawDescOnce sync.Once
	file_proto_beam_beam_node_proto_rawDescData []byte
)

func file_proto_beam_beam_node_proto_rawDescGZIP() []byte {
	file_proto_beam_beam_node_proto_rawDescOnce.Do(func() {
		file_proto_beam_beam_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_beam_beam_node_proto_rawDesc), len(file_proto_beam_beam_node_proto_rawDesc)))
	})
	return file_proto_beam_beam_node_proto_rawDescData
}

var file_proto_beam_beam_node_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_beam_beam_node_proto_goTypes = []any{
	(*BeamAuthReq)(nil),         // 0: dylaris.beam.BeamAuthReq
	(*BeamAuthResp)(nil),        // 1: dylaris.beam.BeamAuthResp
	(*BeamFileListReq)(nil),     // 2: dylaris.beam.BeamFileListReq
	(*BeamFileListResp)(nil),    // 3: dylaris.beam.BeamFileListResp
	(*BeamFileInfo)(nil),        // 4: dylaris.beam.BeamFileInfo
	(*BeamFileReadReq)(nil),     // 5: dylaris.beam.BeamFileReadReq
	(*BeamFileContentResp)(nil), // 6: dylaris.beam.BeamFileContentResp
	(*BeamFileSaveReq)(nil),     // 7: dylaris.beam.BeamFileSaveReq
	(*BeamFileCreateReq)(nil),   // 8: dylaris.beam.BeamFileCreateReq
	(*BeamFileDeleteReq)(nil),   // 9: dylaris.beam.BeamFileDeleteReq
	(*BeamFileRenameReq)(nil),   // 10: dylaris.beam.BeamFileRenameReq
	(*BeamFileCopyReq)(nil),     // 11: dylaris.beam.BeamFileCopyReq
	(*BeamDownloadReq)(nil),     // 12: dylaris.beam.BeamDownloadReq
	(*BeamChunk)(nil),           // 13: dylaris.beam.BeamChunk
	(*BeamUploadMsg)(nil),       // 14: dylaris.beam.BeamUploadMsg
	(*BeamUploadStart)(nil),     // 15: dylaris.beam.BeamUploadStart
	(*BeamUploadChunkData)(nil), // 16: dylaris.beam.BeamUploadChunkData
	(*BeamSelectiveReq)(nil),    // 17: dylaris.beam.BeamSelectiveReq
	(*BeamQuotaReq)(nil),        // 18: dylaris.beam.BeamQuotaReq
	(*BeamQuotaResp)(nil),       // 19: dylaris.beam.BeamQuotaResp
	(*BeamOpResp)(nil),          // 20: dylaris.beam.BeamOpResp
}
var file_proto_beam_beam_node_proto_depIdxs = []int32{
	4,  // 0: dylaris.beam.BeamFileListResp.files:type_name -> dylaris.beam.BeamFileInfo
	15, // 1: dylaris.beam.BeamUploadMsg.start:type_name -> dylaris.beam.BeamUploadStart
	16, // 2: dylaris.beam.BeamUploadMsg.chunk:type_name -> dylaris.beam.BeamUploadChunkData
	0,  // 3: dylaris.beam.BeamNodeService.Authenticate:input_type -> dylaris.beam.BeamAuthReq
	2,  // 4: dylaris.beam.BeamNodeService.ListFiles:input_type -> dylaris.beam.BeamFileListReq
	5,  // 5: dylaris.beam.BeamNodeService.ReadFileContent:input_type -> dylaris.beam.BeamFileReadReq
	7,  // 6: dylaris.beam.BeamNodeService.SaveFileContent:input_type -> dylaris.beam.BeamFileSaveReq
	8,  // 7: dylaris.beam.BeamNodeService.CreateFile:input_type -> dylaris.beam.BeamFileCreateReq
	9,  // 8: dylaris.beam.BeamNodeService.DeleteFile:input_type -> dylaris.beam.BeamFileDeleteReq
	10, // 9: dylaris.beam.BeamNodeService.RenameFile:input_type -> dylaris.beam.BeamFileRenameReq
	11, // 10: dylaris.beam.BeamNodeService.CopyFile:input_type -> dylaris.beam.BeamFileCopyReq
	12, // 11: dylaris.beam.BeamNodeService.DownloadFile:input_type -> dylaris.beam.BeamDownloadReq
	14, // 12: dylaris.beam.BeamNodeService.UploadFile:input_type -> dylaris.beam.BeamUploadMsg
	17, // 13: dylaris.beam.BeamNodeService.DownloadSelective:input_type -> dylaris.beam.BeamSelectiveReq
	18, // 14: dylaris.beam.BeamNodeService.GetTransferQuota:input_type -> dylaris.beam.BeamQuotaReq
	1,  // 15: dylaris.beam.BeamNodeService.Authenticate:output_type -> dylaris.beam.BeamAuthResp
	3,  // 16: dylaris.beam.BeamNodeService.ListFiles:output_type -> dylaris.beam.BeamFileListResp
	6,  // 17: dylaris.beam.BeamNodeService.ReadFileContent:output_type -> dylaris.beam.BeamFileContentResp
	20, // 18: dylaris.beam.BeamNodeService.SaveFileContent:output_type -> dylaris.beam.BeamOpResp
	20, // 19: dylaris.beam.BeamNodeService.CreateFile:output_type -> dylaris.beam.BeamOpResp
	20, // 20: dylaris.beam.BeamNodeService.DeleteFile:output_type -> dylaris.beam.BeamOpResp
	20, // 21: dylaris.beam.BeamNodeService.RenameFile:output_type -> dylaris.beam.BeamOpResp
	20, // 22: dylaris.beam.BeamNodeService.CopyFile:output_type -> dylaris.beam.BeamOpResp
	13, // 23: dylaris.beam.BeamNodeService.DownloadFile:output_type -> dylaris.beam.BeamChunk
	20, // 24: dylaris.beam.BeamNodeService.UploadFile:output_type -> dylaris.beam.BeamOpResp
	13, // 25: dylaris.beam.BeamNodeService.DownloadSelective:output_type -> dylaris.beam.BeamChunk
	19, // 26: dylaris.beam.BeamNodeService.GetTransferQuota:output_type -> dylaris.beam.BeamQuotaResp
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_beam_beam_node_proto_init() }
func file_proto_beam_beam_node_proto_init() {
	if File_proto_beam_beam_node_proto != nil {
		return
	}
	file_proto_beam_beam_node_proto_msgTypes[14].OneofWrappers = []any{
		(*BeamUploadMsg_Start)(nil),
		(*BeamUploadMsg_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_beam_beam_node_proto_rawDesc), len(file_proto_beam_beam_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_beam_beam_node_proto_goTypes,
		DependencyIndexes: file_proto_beam_beam_node_proto_depIdxs,
		MessageInfos:      file_proto_beam_beam_node_proto_msgTypes,
	}.Build()
	File_proto_beam_beam_node_proto = out.File
	file_proto_beam_beam_node_proto_goTypes = nil
	file_proto_beam_beam_node_proto_depIdxs = nil
}
