package handlers

import (
	"fmt"
	"time"

	"github.com/pquerna/otp"
	"github.com/pquerna/otp/totp"
)

// totpDiagnoseSteps is how far either side of now diagnoseRejectedTOTP looks, in
// 30-second TOTP steps. 20 steps = 10 minutes each way, which comfortably covers
// the clock drift a host without working NTP accumulates in a day while staying a
// trivial amount of work on a path that only runs after a rejection.
const totpDiagnoseSteps = 20

// diagnoseRejectedTOTP explains WHY a code was rejected, for the server log.
//
// A rejected TOTP has two very different causes that look identical from the
// outside: the clock is wrong, or the code came from a different secret (a stale
// authenticator entry from an earlier setup attempt, which is easy to produce
// since every wizard open mints a fresh secret). Verifying the same code against
// neighbouring time steps separates them: a hit at a distant offset means the
// clock, a hit nowhere means the secret.
//
// Returns a human sentence for the log. NEVER include the secret or the code:
// this string is written to logs an operator may paste around.
func diagnoseRejectedTOTP(secret, code string, now time.Time) string {
	opts := totp.ValidateOpts{Period: 30, Skew: 0, Digits: otp.DigitsSix, Algorithm: otp.AlgorithmSHA1}
	for off := -totpDiagnoseSteps; off <= totpDiagnoseSteps; off++ {
		if off == 0 {
			continue // already rejected at the current step, with the library's own skew
		}
		t := now.Add(time.Duration(off) * 30 * time.Second)
		ok, err := totp.ValidateCustom(code, secret, t, opts)
		if err != nil || !ok {
			continue
		}
		// Direction, and it is easy to get backwards: a code that is valid at a
		// FUTURE step was generated by a clock ahead of ours, so OUR clock is the
		// one running behind. Naming the wrong side would send the operator to
		// fix time sync on the wrong machine.
		drift := time.Duration(off) * 30 * time.Second
		side := "ahead of"
		if off > 0 {
			side = "behind"
		}
		if drift < 0 {
			drift = -drift
		}
		return fmt.Sprintf(
			"the code is valid for a time step %s away, so this server's clock is roughly %s %s the authenticator's - fix time sync (NTP) on the Core host",
			drift, drift, side)
	}
	return "the code matches no time step within " +
		(time.Duration(totpDiagnoseSteps) * 30 * time.Second).String() +
		" either way, so it was generated from a DIFFERENT secret (a leftover authenticator entry from an earlier setup attempt) or simply mistyped - delete the old entry and scan the QR shown now"
}
