// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeamUploadCancel(arg1) {
  return window['go']['main']['App']['BeamUploadCancel'](arg1);
}

export function BeamUploadChunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['BeamUploadChunk'](arg1, arg2, arg3);
}

export function BeamUploadFinish(arg1) {
  return window['go']['main']['App']['BeamUploadFinish'](arg1);
}

export function BeamUploadStart(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BeamUploadStart'](arg1, arg2, arg3, arg4, arg5);
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2, arg3);
}

export function CreateFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2, arg3);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function GetBeamConfig() {
  return window['go']['main']['App']['GetBeamConfig']();
}

export function GetBeamTicket(arg1) {
  return window['go']['main']['App']['GetBeamTicket'](arg1);
}

export function GetFileContent(arg1, arg2) {
  return window['go']['main']['App']['GetFileContent'](arg1, arg2);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}
