// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BeamUploadCancel(arg1:string):Promise<void>;

export function BeamUploadChunk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function BeamUploadFinish(arg1:string):Promise<void>;

export function BeamUploadStart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function CopyFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateFile(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function GetBeamConfig():Promise<main.BeamConfig>;

export function GetBeamTicket(arg1:string):Promise<string>;

export function GetFileContent(arg1:string,arg2:string):Promise<main.FileContentResult>;

export function GetServers():Promise<Array<main.BeamServer>>;

export function IsLoggedIn():Promise<boolean>;

export function ListFiles(arg1:string,arg2:string):Promise<main.FileListResult>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<void>;
