package main

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

type InstallerConfig struct {
	Type      string `json:"type"`      // "paper", "vanilla", "library", "upload", "upload-zip", "import"
	Version   string `json:"version"`   // e.g. "1.21.1"
	URL       string `json:"url"`       // Direct download URL (for "import" / library fallback)
	Path      string `json:"path"`      // Local library file path (for "library" type)
	Structure string `json:"structure"` // "direct" or "subfolder" (for "upload-zip")
}

// CleanServerJars removes server JARs and cached/generated directories while preserving
// user data like worlds, plugins, mods, configs, etc.
func CleanServerJars(subServerDir string) error {
	// Directories to remove (generated by the server / installer)
	// Note: "libraries" is kept — Forge/NeoForge needs it for runtime dependencies
	removeDirs := []string{"versions", "cache", ".fabric", ".gradle"}
	for _, dir := range removeDirs {
		p := filepath.Join(subServerDir, dir)
		if _, err := os.Stat(p); err == nil {
			log.Printf("Removing directory: %s", dir)
			os.RemoveAll(p)
		}
	}

	// Remove all JAR files in the root of the sub-server directory
	entries, err := os.ReadDir(subServerDir)
	if err != nil {
		return fmt.Errorf("failed to read sub-server dir: %v", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(strings.ToLower(entry.Name()), ".jar") {
			p := filepath.Join(subServerDir, entry.Name())
			log.Printf("Removing JAR: %s", entry.Name())
			os.Remove(p)
		}
	}

	return nil
}

// InstallServer installs the server software into <serverDataPath>/<subServerName>/.
// For "upload" type, files are already in place via HTTP upload — nothing to do.
func InstallServer(serverDataPath, subServerName string, config InstallerConfig) error {
	destDir := filepath.Join(serverDataPath, subServerName)
	if err := os.MkdirAll(destDir, 0755); err != nil {
		return fmt.Errorf("failed to create server dir: %v", err)
	}

	log.Printf("Starting Installation: %s (%s) -> %s", config.Type, config.Version, destDir)

	switch config.Type {
	case "paper":
		return installPaper(destDir, config.Version)
	case "vanilla":
		return installVanilla(destDir, config.Version)
	case "library":
		return installFromLibrary(destDir, config.Path, config.URL)
	case "import":
		if config.URL == "" {
			return fmt.Errorf("import type requires a URL")
		}
		return installFromURL(destDir, config.URL)
	case "upload":
		// Files pre-uploaded via HTTP to the sub-server directory — nothing to do here.
		log.Printf("Upload type: files already in %s, skipping installer", destDir)
		return nil
	case "upload-zip":
		return installFromUploadZip(destDir, config.Structure)
	default:
		return fmt.Errorf("unknown installer type: %s", config.Type)
	}
}

// installPaper fetches the latest PaperMC build for the given version and downloads it as server.jar.
func installPaper(dir, version string) error {
	apiURL := fmt.Sprintf("https://api.papermc.io/v2/projects/paper/versions/%s/builds", version)
	resp, err := http.Get(apiURL)
	if err != nil {
		return fmt.Errorf("failed to query PaperMC API: %v", err)
	}
	defer resp.Body.Close()

	var result struct {
		Builds []struct {
			Build     int `json:"build"`
			Downloads struct {
				Application struct {
					Name string `json:"name"`
				} `json:"application"`
			} `json:"downloads"`
		} `json:"builds"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return fmt.Errorf("failed to parse PaperMC response: %v", err)
	}
	if len(result.Builds) == 0 {
		return fmt.Errorf("no builds found for Paper %s", version)
	}

	latest := result.Builds[len(result.Builds)-1]
	fileName := latest.Downloads.Application.Name
	downloadURL := fmt.Sprintf(
		"https://api.papermc.io/v2/projects/paper/versions/%s/builds/%d/downloads/%s",
		version, latest.Build, fileName,
	)

	log.Printf("Downloading PaperMC %s build %d ...", version, latest.Build)
	return downloadFile(downloadURL, filepath.Join(dir, "server.jar"))
}

// installVanilla downloads the official Minecraft server jar via Mojang's launcher manifest.
func installVanilla(dir, version string) error {
	const manifestURL = "https://launchermeta.mojang.com/mc/game/version_manifest.json"

	resp, err := http.Get(manifestURL)
	if err != nil {
		return fmt.Errorf("failed to fetch Mojang manifest: %v", err)
	}
	defer resp.Body.Close()

	var manifest struct {
		Versions []struct {
			ID  string `json:"id"`
			URL string `json:"url"`
		} `json:"versions"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&manifest); err != nil {
		return fmt.Errorf("failed to parse Mojang manifest: %v", err)
	}

	var versionURL string
	for _, v := range manifest.Versions {
		if v.ID == version {
			versionURL = v.URL
			break
		}
	}
	if versionURL == "" {
		return fmt.Errorf("vanilla version %s not found in Mojang manifest", version)
	}

	resp2, err := http.Get(versionURL)
	if err != nil {
		return fmt.Errorf("failed to fetch version info for %s: %v", version, err)
	}
	defer resp2.Body.Close()

	var versionInfo struct {
		Downloads struct {
			Server struct {
				URL string `json:"url"`
			} `json:"server"`
		} `json:"downloads"`
	}
	if err := json.NewDecoder(resp2.Body).Decode(&versionInfo); err != nil {
		return fmt.Errorf("failed to parse version info: %v", err)
	}
	if versionInfo.Downloads.Server.URL == "" {
		return fmt.Errorf("no server download available for vanilla %s", version)
	}

	log.Printf("Downloading Vanilla Minecraft %s ...", version)
	return downloadFile(versionInfo.Downloads.Server.URL, filepath.Join(dir, "server.jar"))
}

// installFromLibrary copies a library file (JAR or ZIP) into the server directory.
// localPath takes priority; fallbackURL is used when localPath is empty.
func installFromLibrary(destDir, localPath, fallbackURL string) error {
	if localPath != "" {
		return installFromLocalFile(destDir, localPath)
	}
	if fallbackURL != "" {
		return installFromURL(destDir, fallbackURL)
	}
	return fmt.Errorf("library installer: no path or URL provided")
}

// installFromLocalFile copies a local file (JAR or ZIP) or directory into destDir.
func installFromLocalFile(destDir, srcPath string) error {
	info, err := os.Stat(srcPath)
	if err != nil {
		return fmt.Errorf("library source not found: %v", err)
	}
	if info.IsDir() {
		log.Printf("Copying directory from library: %s", srcPath)
		return copyDir(srcPath, destDir)
	}
	lower := strings.ToLower(srcPath)
	if strings.HasSuffix(lower, ".zip") {
		log.Printf("Extracting ZIP from library: %s", srcPath)
		return extractZipToDir(srcPath, destDir)
	}
	// Assume it's a JAR or similar — place it as server.jar
	log.Printf("Copying JAR from library: %s", srcPath)
	return copyFile(srcPath, filepath.Join(destDir, "server.jar"))
}

// installFromURL downloads a file from a URL and places it in destDir.
// ZIPs are extracted automatically; other files are saved as server.jar.
func installFromURL(destDir, url string) error {
	lower := strings.ToLower(url)

	var destPath string
	if strings.HasSuffix(lower, ".zip") {
		destPath = filepath.Join(destDir, "_download.zip")
	} else {
		destPath = filepath.Join(destDir, "server.jar")
	}

	log.Printf("Downloading from URL: %s ...", url)
	if err := downloadFile(url, destPath); err != nil {
		return err
	}

	if strings.HasSuffix(destPath, ".zip") {
		log.Printf("Extracting downloaded ZIP ...")
		if err := extractZipToDir(destPath, destDir); err != nil {
			return err
		}
		os.Remove(destPath)
	}
	return nil
}

// installFromUploadZip extracts a pre-uploaded .upload.zip in the sub-server directory.
// If structure is "subfolder", it detects a single top-level folder and moves its contents up.
func installFromUploadZip(destDir, structure string) error {
	zipPath := filepath.Join(destDir, ".upload.zip")
	if _, err := os.Stat(zipPath); err != nil {
		return fmt.Errorf("upload zip not found at %s", zipPath)
	}

	log.Printf("Extracting uploaded ZIP: %s (structure=%s)", zipPath, structure)
	if err := extractZipToDir(zipPath, destDir); err != nil {
		return fmt.Errorf("failed to extract upload zip: %v", err)
	}
	os.Remove(zipPath)

	// If structure is "subfolder", check for a single top-level directory and move contents up
	if structure == "subfolder" {
		entries, err := os.ReadDir(destDir)
		if err != nil {
			return nil // extraction succeeded, this is non-critical
		}
		var dirs []os.DirEntry
		for _, e := range entries {
			if e.IsDir() {
				dirs = append(dirs, e)
			}
		}
		if len(dirs) == 1 {
			subDir := filepath.Join(destDir, dirs[0].Name())
			log.Printf("Moving contents from subfolder: %s", dirs[0].Name())
			subEntries, err := os.ReadDir(subDir)
			if err != nil {
				return nil
			}
			for _, e := range subEntries {
				src := filepath.Join(subDir, e.Name())
				dst := filepath.Join(destDir, e.Name())
				os.Rename(src, dst)
			}
			os.Remove(subDir)
		}
	}

	return nil
}

// DetectServerJar scans the server directory for the main JAR file.
// Returns the detected JAR filename (e.g. "forge-1.20.1-47.2.0-shim.jar") or "server.jar" as fallback.
func DetectServerJar(destDir string) string {
	patterns := []string{
		"forge-*-shim.jar",          // Forge 1.17+ (new launcher)
		"forge-*-universal.jar",     // Forge legacy
		"neoforge-*.jar",            // NeoForge
		"fabric-server-launch.jar",  // Fabric
		"paper-*.jar",               // Paper
		"purpur-*.jar",              // Purpur
		"server.jar",                // Default
	}
	for _, pattern := range patterns {
		matches, _ := filepath.Glob(filepath.Join(destDir, pattern))
		if len(matches) > 0 {
			jar := filepath.Base(matches[0])
			log.Printf("Detected server JAR: %s", jar)
			return jar
		}
	}
	return "server.jar"
}

// DetectExtraJvmArgs reads Forge's user_jvm_args.txt and returns additional JVM flags.
// Filters out -Xmx/-Xms (we control RAM allocation ourselves) and comments.
func DetectExtraJvmArgs(destDir string) string {
	argsFile := filepath.Join(destDir, "user_jvm_args.txt")
	data, err := os.ReadFile(argsFile)
	if err != nil {
		return ""
	}

	var args []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Skip memory flags — we set those via -Xmx from the DB
		if strings.HasPrefix(line, "-Xmx") || strings.HasPrefix(line, "-Xms") {
			continue
		}
		args = append(args, line)
	}
	if len(args) > 0 {
		log.Printf("Detected JVM args from user_jvm_args.txt: %s", strings.Join(args, " "))
	}
	return strings.Join(args, " ")
}

// extractZipToDir extracts a ZIP archive into destDir, guarding against path traversal.
func extractZipToDir(zipPath, destDir string) error {
	r, err := zip.OpenReader(zipPath)
	if err != nil {
		return fmt.Errorf("failed to open zip %s: %v", zipPath, err)
	}
	defer r.Close()

	destDir = filepath.Clean(destDir)

	for _, f := range r.File {
		fPath := filepath.Join(destDir, f.Name)
		// Path traversal guard
		if !strings.HasPrefix(filepath.Clean(fPath), destDir+string(os.PathSeparator)) {
			log.Printf("Skipping unsafe zip entry: %s", f.Name)
			continue
		}

		if f.FileInfo().IsDir() {
			os.MkdirAll(fPath, 0755)
			continue
		}

		if err := os.MkdirAll(filepath.Dir(fPath), 0755); err != nil {
			return err
		}

		outFile, err := os.OpenFile(fPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
		if err != nil {
			return err
		}

		rc, err := f.Open()
		if err != nil {
			outFile.Close()
			return err
		}

		_, copyErr := io.Copy(outFile, rc)
		rc.Close()
		outFile.Close()
		if copyErr != nil {
			return copyErr
		}
	}
	return nil
}

// copyFile copies a single file from src to dst.
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}

// copyDir recursively copies src directory into dst.
func copyDir(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, info.Mode())
		}
		return copyFile(path, target)
	})
}

// downloadFile downloads a URL to a local file path.
func downloadFile(url, destPath string) error {
	out, err := os.Create(destPath)
	if err != nil {
		return err
	}
	defer out.Close()

	resp, err := http.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("bad status: %s", resp.Status)
	}

	_, err = io.Copy(out, resp.Body)
	return err
}
