import {
  type LucideIcon,
  House, Server, PlusCircle, Wrench, ChevronDown, ChevronUp,
  UserCog, LogOut, Pencil, SlidersHorizontal, Trash2, AlertTriangle,
  Play, Square, RotateCcw, Skull, Cpu, MemoryStick, HardDrive,
  Terminal, FolderOpen, Folder, Settings, Users, ShieldCheck,
  Search, X, Plus, CircleCheck, ArrowRight, Rocket, Info,
  UserPlus, UserMinus, Send, Power, FolderPlus, Upload,
  ArrowUp, ArrowDown, Archive, RefreshCw, Network, Globe,
  Cable, Save, CircleAlert, PlayCircle, PackageOpen, Grid2x2, Ticket,
  FileText, File, CornerDownLeft, ExternalLink, FilePen, Copy,
  Download, Check, CircleHelp, Link, SquareTerminal,
} from 'lucide-react';

// Map: string name → Lucide component
// Includes both Lucide names (kebab-case) and Material Symbol names (snake_case) as aliases
export const iconMap: Record<string, LucideIcon> = {
  // Lucide canonical names
  'house': House,
  'server': Server,
  'plus-circle': PlusCircle,
  'wrench': Wrench,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'user-cog': UserCog,
  'log-out': LogOut,
  'pencil': Pencil,
  'sliders-horizontal': SlidersHorizontal,
  'trash-2': Trash2,
  'alert-triangle': AlertTriangle,
  'play': Play,
  'square': Square,
  'rotate-ccw': RotateCcw,
  'skull': Skull,
  'cpu': Cpu,
  'memory-stick': MemoryStick,
  'hard-drive': HardDrive,
  'terminal': Terminal,
  'square-terminal': SquareTerminal,
  'folder-open': FolderOpen,
  'folder': Folder,
  'settings': Settings,
  'users': Users,
  'shield-check': ShieldCheck,
  'search': Search,
  'x': X,
  'plus': Plus,
  'circle-check': CircleCheck,
  'arrow-right': ArrowRight,
  'rocket': Rocket,
  'info': Info,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'send': Send,
  'power': Power,
  'folder-plus': FolderPlus,
  'upload': Upload,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'archive': Archive,
  'refresh-cw': RefreshCw,
  'network': Network,
  'globe': Globe,
  'cable': Cable,
  'save': Save,
  'circle-alert': CircleAlert,
  'play-circle': PlayCircle,
  'package-open': PackageOpen,
  'grid-2x2': Grid2x2,
  'file-text': FileText,
  'file': File,
  'corner-down-left': CornerDownLeft,
  'external-link': ExternalLink,
  'file-pen': FilePen,
  'copy': Copy,
  'download': Download,
  'check': Check,
  'circle-help': CircleHelp,
  'link': Link,
  'ticket': Ticket,

  // Material Symbol aliases (backward compat with DB values)
  'dashboard': House,
  'dns': Server,
  'add_circle': PlusCircle,
  'build': Wrench,
  'build_circle': Wrench,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'manage_accounts': UserCog,
  'logout': LogOut,
  'edit': Pencil,
  'tune': SlidersHorizontal,
  'delete': Trash2,
  'warning': AlertTriangle,
  'play_arrow': Play,
  'stop': Square,
  'restart_alt': RotateCcw,
  'dangerous': Skull,
  'memory': Cpu,
  'memory_alt': MemoryStick,
  'hard_drive': HardDrive,
  'folder_open': FolderOpen,
  'group_add': Users,
  'group': Users,
  'admin_panel_settings': ShieldCheck,
  'close': X,
  'add': Plus,
  'check_circle': CircleCheck,
  'arrow_forward': ArrowRight,
  'rocket_launch': Rocket,
  'person_add': UserPlus,
  'person_remove': UserMinus,
  'power_settings_new': Power,
  'create_new_folder': FolderPlus,
  'arrow_upward': ArrowUp,
  'arrow_downward': ArrowDown,
  'sync': RefreshCw,
  'hub': Network,
  'language': Globe,
  'error': CircleAlert,
  'play_circle': PlayCircle,
  'deployed_code': PackageOpen,
  'grid_view': Grid2x2,
  'text_snippet': FileText,
  'draft': File,
  'subdirectory_arrow_left': CornerDownLeft,
  'shortcut': ExternalLink,
  'drive_file_rename_outline': FilePen,
  'content_copy': Copy,
  'help': CircleHelp,
  'confirmation_number': Ticket,
  'extension': PackageOpen,
};

export function DynamicIcon({ name, size = 20, className, style }: {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Icon = iconMap[name] || Grid2x2;
  return <Icon size={size} className={className} style={style} />;
}
