import {
  type LucideIcon,
  House, Server, PlusCircle, Wrench, ChevronDown, ChevronUp,
  UserCog, LogOut, Pencil, SlidersHorizontal, Trash2, AlertTriangle,
  Play, Square, RotateCcw, Skull, Cpu, MemoryStick, HardDrive,
  Terminal, FolderOpen, Folder, Settings, Users, ShieldCheck,
  Search, X, Plus, CircleCheck, ArrowRight, Rocket, Info,
  UserPlus, UserMinus, Send, Power, FolderPlus, Upload,
  ArrowUp, ArrowDown, Archive, RefreshCw, Network, Globe,
  Cable, Save, CircleAlert, PlayCircle, PackageOpen, Grid2x2, Ticket,
  FileText, File, CornerDownLeft, ExternalLink, FilePen, Copy,
  Download, Check, CircleHelp, Link, SquareTerminal,
  // Picker set: everything TAB_ICON_NAMES offers. Named imports, not the
  // dynamic `icons` registry - that one defeats tree-shaking and would pull
  // all ~1700 into the bundle for a dropdown.
  Map, MapPin, Compass, Earth, Navigation, Route, Signpost, Gauge,
  Activity, ChartLine, ChartBar, ChartPie, TrendingUp, Sparkles, Zap,
  Flame, Bolt, User, UserCheck, Crown, Shield, ShieldAlert, Swords, Sword,
  Axe, Gem, Trophy, Medal, Target, Crosshair, Database, Router, Wifi, Plug,
  Antenna, Radio, SatelliteDish, Code, Braces, FileCode, Bug, Hammer,
  ToggleLeft, Cog, Package, Boxes, Box, Container, Layers, Blocks,
  LayoutGrid, LayoutDashboard, PanelsTopLeft, Files, Book, BookOpen,
  Notebook, Scroll, ClipboardList, List, ListChecks, Calendar, Clock,
  Timer, History, Bell, Mail, MessageSquare, MessagesSquare, Megaphone,
  Inbox, Heart, Star, Bookmark, Flag, Pin, Tag, Tags, Gift, ShoppingCart,
  CreditCard, Coins, Wallet, Lock, Key, KeyRound, Eye, EyeOff, Scan,
  Funnel, Pause, CircleStop, Cloud, CloudUpload, CloudDownload, Share2,
  Image, Camera, Video, Music, Headphones, Mic, Volume2, Palette, Brush,
  WandSparkles, Monitor, Laptop, Smartphone, Tablet, Tv, Gamepad2,
  Joystick, Dices, Puzzle, Plane, Ship, Truck, Car, TreePine, Leaf, Sprout,
  Sun, Moon, CloudRain, Snowflake, Droplet, Mountain, Waves, Anchor,
  Pickaxe, Shovel, Tent, Castle, Building, Store, Warehouse, LifeBuoy,
  TriangleAlert, CircleX, ThumbsUp, Smile, Coffee, Pizza, Apple, Beaker,
  FlaskConical, Atom, Brain, Bot,
} from 'lucide-react';

// Map: string name → Lucide component
// Includes both Lucide names (kebab-case) and Material Symbol names (snake_case) as aliases
export const iconMap: Record<string, LucideIcon> = {
  // Lucide canonical names
  'house': House,
  'server': Server,
  'plus-circle': PlusCircle,
  'wrench': Wrench,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'user-cog': UserCog,
  'log-out': LogOut,
  'pencil': Pencil,
  'sliders-horizontal': SlidersHorizontal,
  'trash-2': Trash2,
  'alert-triangle': AlertTriangle,
  'play': Play,
  'square': Square,
  'rotate-ccw': RotateCcw,
  'skull': Skull,
  'cpu': Cpu,
  'memory-stick': MemoryStick,
  'hard-drive': HardDrive,
  'terminal': Terminal,
  'square-terminal': SquareTerminal,
  'folder-open': FolderOpen,
  'folder': Folder,
  'settings': Settings,
  'users': Users,
  'shield-check': ShieldCheck,
  'search': Search,
  'x': X,
  'plus': Plus,
  'circle-check': CircleCheck,
  'arrow-right': ArrowRight,
  'rocket': Rocket,
  'info': Info,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'send': Send,
  'power': Power,
  'folder-plus': FolderPlus,
  'upload': Upload,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'archive': Archive,
  'refresh-cw': RefreshCw,
  'network': Network,
  'globe': Globe,
  'cable': Cable,
  'save': Save,
  'circle-alert': CircleAlert,
  'play-circle': PlayCircle,
  'package-open': PackageOpen,
  'grid-2x2': Grid2x2,
  'file-text': FileText,
  'file': File,
  'corner-down-left': CornerDownLeft,
  'external-link': ExternalLink,
  'file-pen': FilePen,
  'copy': Copy,
  'download': Download,
  'check': Check,
  'circle-help': CircleHelp,
  'link': Link,
  'ticket': Ticket,

  // Material Symbol aliases (backward compat with DB values)
  'dashboard': House,
  'dns': Server,
  'add_circle': PlusCircle,
  'build': Wrench,
  'build_circle': Wrench,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'manage_accounts': UserCog,
  'logout': LogOut,
  'edit': Pencil,
  'tune': SlidersHorizontal,
  'delete': Trash2,
  'warning': AlertTriangle,
  'play_arrow': Play,
  'stop': Square,
  'restart_alt': RotateCcw,
  'dangerous': Skull,
  'memory': Cpu,
  'memory_alt': MemoryStick,
  'hard_drive': HardDrive,
  'folder_open': FolderOpen,
  'group_add': Users,
  'group': Users,
  'admin_panel_settings': ShieldCheck,
  'close': X,
  'add': Plus,
  'check_circle': CircleCheck,
  'arrow_forward': ArrowRight,
  'rocket_launch': Rocket,
  'person_add': UserPlus,
  'person_remove': UserMinus,
  'power_settings_new': Power,
  'create_new_folder': FolderPlus,
  'arrow_upward': ArrowUp,
  'arrow_downward': ArrowDown,
  'sync': RefreshCw,
  'hub': Network,
  'language': Globe,
  'error': CircleAlert,
  'play_circle': PlayCircle,
  'deployed_code': PackageOpen,
  'grid_view': Grid2x2,
  'text_snippet': FileText,
  'draft': File,
  'subdirectory_arrow_left': CornerDownLeft,
  'shortcut': ExternalLink,
  'drive_file_rename_outline': FilePen,
  'content_copy': Copy,
  'help': CircleHelp,
  'confirmation_number': Ticket,
  'extension': PackageOpen,

  // ── Custom-tab picker set ──────────────────────────────────────────
  'map': Map,
  'map-pin': MapPin,
  'compass': Compass,
  'earth': Earth,
  'navigation': Navigation,
  'route': Route,
  'signpost': Signpost,
  'gauge': Gauge,
  'activity': Activity,
  'chart-line': ChartLine,
  'chart-bar': ChartBar,
  'chart-pie': ChartPie,
  'trending-up': TrendingUp,
  'sparkles': Sparkles,
  'zap': Zap,
  'flame': Flame,
  'bolt': Bolt,
  'user': User,
  'user-check': UserCheck,
  'crown': Crown,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'swords': Swords,
  'sword': Sword,
  'axe': Axe,
  'gem': Gem,
  'trophy': Trophy,
  'medal': Medal,
  'target': Target,
  'crosshair': Crosshair,
  'database': Database,
  'router': Router,
  'wifi': Wifi,
  'plug': Plug,
  'antenna': Antenna,
  'radio': Radio,
  'satellite-dish': SatelliteDish,
  'code': Code,
  'braces': Braces,
  'file-code': FileCode,
  'bug': Bug,
  'hammer': Hammer,
  'toggle-left': ToggleLeft,
  'cog': Cog,
  'package': Package,
  'boxes': Boxes,
  'box': Box,
  'container': Container,
  'layers': Layers,
  'blocks': Blocks,
  'layout-grid': LayoutGrid,
  'layout-dashboard': LayoutDashboard,
  'panels-top-left': PanelsTopLeft,
  'files': Files,
  'book': Book,
  'book-open': BookOpen,
  'notebook': Notebook,
  'scroll': Scroll,
  'clipboard-list': ClipboardList,
  'list': List,
  'list-checks': ListChecks,
  'calendar': Calendar,
  'clock': Clock,
  'timer': Timer,
  'history': History,
  'bell': Bell,
  'mail': Mail,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  'megaphone': Megaphone,
  'inbox': Inbox,
  'heart': Heart,
  'star': Star,
  'bookmark': Bookmark,
  'flag': Flag,
  'pin': Pin,
  'tag': Tag,
  'tags': Tags,
  'gift': Gift,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'coins': Coins,
  'wallet': Wallet,
  'lock': Lock,
  'key': Key,
  'key-round': KeyRound,
  'eye': Eye,
  'eye-off': EyeOff,
  'scan': Scan,
  'funnel': Funnel,
  'pause': Pause,
  'circle-stop': CircleStop,
  'cloud': Cloud,
  'cloud-upload': CloudUpload,
  'cloud-download': CloudDownload,
  'share-2': Share2,
  'image': Image,
  'camera': Camera,
  'video': Video,
  'music': Music,
  'headphones': Headphones,
  'mic': Mic,
  'volume-2': Volume2,
  'palette': Palette,
  'brush': Brush,
  'wand-sparkles': WandSparkles,
  'monitor': Monitor,
  'laptop': Laptop,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'tv': Tv,
  'gamepad-2': Gamepad2,
  'joystick': Joystick,
  'dices': Dices,
  'puzzle': Puzzle,
  'plane': Plane,
  'ship': Ship,
  'truck': Truck,
  'car': Car,
  'tree-pine': TreePine,
  'leaf': Leaf,
  'sprout': Sprout,
  'sun': Sun,
  'moon': Moon,
  'cloud-rain': CloudRain,
  'snowflake': Snowflake,
  'droplet': Droplet,
  'mountain': Mountain,
  'waves': Waves,
  'anchor': Anchor,
  'pickaxe': Pickaxe,
  'shovel': Shovel,
  'tent': Tent,
  'castle': Castle,
  'building': Building,
  'store': Store,
  'warehouse': Warehouse,
  'life-buoy': LifeBuoy,
  'triangle-alert': TriangleAlert,
  'circle-x': CircleX,
  'thumbs-up': ThumbsUp,
  'smile': Smile,
  'coffee': Coffee,
  'pizza': Pizza,
  'apple': Apple,
  'beaker': Beaker,
  'flask-conical': FlaskConical,
  'atom': Atom,
  'brain': Brain,
  'bot': Bot,
};

/**
 * What the custom-tab icon picker offers, in a deliberate order (places,
 * measurement, people, hardware, files, ...) so scanning it is not alphabet
 * soup.
 *
 * Canonical Lucide names only. iconMap also holds Material-Symbol aliases
 * pointing at the SAME components, and offering both would put visually
 * identical entries in the grid under two names.
 */
export const TAB_ICON_NAMES: string[] = [
    'map',
    'map-pin',
    'globe',
    'compass',
    'earth',
    'navigation',
    'route',
    'signpost',
    'gauge',
    'activity',
    'chart-line',
    'chart-bar',
    'chart-pie',
    'trending-up',
    'sparkles',
    'zap',
    'flame',
    'bolt',
    'users',
    'user',
    'user-check',
    'crown',
    'shield',
    'shield-check',
    'shield-alert',
    'swords',
    'sword',
    'axe',
    'gem',
    'trophy',
    'medal',
    'target',
    'crosshair',
    'server',
    'database',
    'hard-drive',
    'cpu',
    'memory-stick',
    'network',
    'router',
    'wifi',
    'cable',
    'plug',
    'antenna',
    'radio',
    'satellite-dish',
    'terminal',
    'square-terminal',
    'code',
    'braces',
    'file-code',
    'bug',
    'wrench',
    'hammer',
    'settings',
    'sliders-horizontal',
    'toggle-left',
    'cog',
    'package',
    'package-open',
    'boxes',
    'box',
    'container',
    'layers',
    'blocks',
    'grid-2x2',
    'layout-grid',
    'layout-dashboard',
    'panels-top-left',
    'folder',
    'folder-open',
    'file',
    'file-text',
    'files',
    'archive',
    'book',
    'book-open',
    'notebook',
    'scroll',
    'clipboard-list',
    'list',
    'list-checks',
    'calendar',
    'clock',
    'timer',
    'history',
    'bell',
    'mail',
    'message-square',
    'messages-square',
    'megaphone',
    'send',
    'inbox',
    'heart',
    'star',
    'bookmark',
    'flag',
    'pin',
    'tag',
    'tags',
    'ticket',
    'gift',
    'shopping-cart',
    'credit-card',
    'coins',
    'wallet',
    'lock',
    'key',
    'key-round',
    'eye',
    'eye-off',
    'scan',
    'search',
    'funnel',
    'play',
    'pause',
    'circle-stop',
    'refresh-cw',
    'rotate-ccw',
    'power',
    'upload',
    'download',
    'cloud',
    'cloud-upload',
    'cloud-download',
    'share-2',
    'link',
    'external-link',
    'image',
    'camera',
    'video',
    'music',
    'headphones',
    'mic',
    'volume-2',
    'palette',
    'brush',
    'wand-sparkles',
    'monitor',
    'laptop',
    'smartphone',
    'tablet',
    'tv',
    'gamepad-2',
    'joystick',
    'dices',
    'puzzle',
    'rocket',
    'plane',
    'ship',
    'truck',
    'car',
    'tree-pine',
    'leaf',
    'sprout',
    'sun',
    'moon',
    'cloud-rain',
    'snowflake',
    'droplet',
    'mountain',
    'waves',
    'anchor',
    'pickaxe',
    'shovel',
    'tent',
    'castle',
    'house',
    'building',
    'store',
    'warehouse',
    'life-buoy',
    'info',
    'triangle-alert',
    'circle-check',
    'circle-x',
    'circle-alert',
    'thumbs-up',
    'smile',
    'coffee',
    'pizza',
    'apple',
    'beaker',
    'flask-conical',
    'atom',
    'brain',
    'bot',
];

export function DynamicIcon({ name, size = 20, className, style }: {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Icon = iconMap[name] || Grid2x2;
  return <Icon size={size} className={className} style={style} />;
}
