package apidoc

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// Render turns the parsed routes into the reference document. preamble is the
// hand-written prose that goes above the generated tables; everything below it
// is derived and must not be edited by hand.
func Render(routes []Route, preamble string) string {
	var b strings.Builder

	b.WriteString("# DYLARIS Core HTTP API\n\n")
	b.WriteString("<!-- GENERATED BY core/cmd/apidocs. DO NOT EDIT BELOW THE PREAMBLE. -->\n")
	b.WriteString("<!-- Regenerate: cd platform/core && go run ./cmd/apidocs -->\n\n")
	b.WriteString(strings.TrimSpace(preamble))
	b.WriteString("\n\n")

	sections := groupByPrefix(routes)
	writeSummary(&b, routes, sections)
	writeContents(&b, sections)

	for _, s := range sections {
		fmt.Fprintf(&b, "## %s\n\n", s.title)
		b.WriteString("| Method | Path | Auth | Capability | Gates | Handler | Notes |\n")
		b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
		for _, r := range s.routes {
			writeRow(&b, r)
		}
		b.WriteString("\n")
	}
	return b.String()
}

type section struct {
	title  string
	anchor string
	routes []Route
}

// groupKey is the resource a route belongs to: the first two path segments, or
// the whole path when it has only one.
//
// The obvious alternative was the "// --- ... ---" banners in routes.go, and it
// was tried and dropped: 33 banners cover 461 routes, so a long unbannered
// stretch inherits whichever banner happens to sit above it. That put 29
// /api/servers routes and 16 /api/nodes routes under a heading about ticket
// database migration. A reader looks an endpoint up by its path.
func groupKey(path string) string {
	parts := strings.Split(strings.TrimPrefix(path, "/"), "/")
	if len(parts) < 2 {
		return "/" + parts[0]
	}
	return "/" + parts[0] + "/" + parts[1]
}

// groupByPrefix sorts groups and their routes by path, so the document reads as
// a lookup table rather than as a transcript of the registration order.
func groupByPrefix(routes []Route) []section {
	byKey := map[string][]Route{}
	for _, r := range routes {
		k := groupKey(r.Path)
		byKey[k] = append(byKey[k], r)
	}
	order := make([]string, 0, len(byKey))
	for k := range byKey {
		order = append(order, k)
	}
	sort.Strings(order)

	used := map[string]int{}
	out := make([]section, 0, len(order))
	for _, title := range order {
		rs := byKey[title]
		sort.SliceStable(rs, func(i, j int) bool {
			if rs[i].Path != rs[j].Path {
				return rs[i].Path < rs[j].Path
			}
			return methodRank(rs[i].Methods) < methodRank(rs[j].Methods)
		})
		out = append(out, section{title: title, anchor: anchor(title, used), routes: rs})
	}
	return out
}

var methodOrder = map[string]int{"GET": 0, "HEAD": 1, "POST": 2, "PUT": 3, "PATCH": 4, "DELETE": 5}

func methodRank(methods []string) int {
	if len(methods) == 0 {
		return 99
	}
	if r, ok := methodOrder[methods[0]]; ok {
		return r
	}
	return 98
}

var anchorStrip = regexp.MustCompile(`[^a-z0-9 -]`)

// anchor reproduces the GitHub heading-slug rule, including its numeric suffix
// for repeats, so the contents list actually links.
func anchor(title string, used map[string]int) string {
	s := anchorStrip.ReplaceAllString(strings.ToLower(title), "")
	s = strings.ReplaceAll(strings.TrimSpace(s), " ", "-")
	used[s]++
	if n := used[s]; n > 1 {
		s = fmt.Sprintf("%s-%d", s, n-1)
	}
	return s
}

func writeSummary(b *strings.Builder, routes []Route, sections []section) {
	byMethod := map[string]int{}
	public, capped, undocumented := 0, 0, 0
	byAuthz := map[string]int{}
	for _, r := range routes {
		byAuthz[r.Authz]++
		for _, m := range r.Methods {
			byMethod[m]++
		}
		if len(r.Methods) == 0 {
			byMethod["(any)"]++
		}
		if r.Auth == "" {
			public++
		}
		if r.Cap != "" {
			capped++
		}
		if r.Doc == "" {
			undocumented++
		}
	}
	methods := make([]string, 0, len(byMethod))
	for m := range byMethod {
		methods = append(methods, m)
	}
	sort.Slice(methods, func(i, j int) bool { return methodRank([]string{methods[i]}) < methodRank([]string{methods[j]}) })

	parts := make([]string, 0, len(methods))
	for _, m := range methods {
		parts = append(parts, fmt.Sprintf("%d %s", byMethod[m], m))
	}

	b.WriteString("## At a glance\n\n")
	fmt.Fprintf(b, "- **%d routes** in %d sections: %s.\n", len(routes), len(sections), strings.Join(parts, ", "))
	fmt.Fprintf(b, "- **%d** accept no credential at all; read the Gates column before assuming any of them is open.\n", public)
	fmt.Fprintf(b, "- **%d** declare a capability at the route, **%d** enforce authorization inside the handler, **%d** are deliberately exempt, and **%d** carry no capability of their own because the one registered for their path template guards a different method on it.\n",
		capped, byAuthz["in-handler"], byAuthz["exempt"], byAuthz["uncapped method"])
	fmt.Fprintf(b, "- **%d** have no usable description yet. Fix one by writing the handler's doc comment, not this file.\n\n", undocumented)
}

func writeContents(b *strings.Builder, sections []section) {
	b.WriteString("## Contents\n\n")
	for _, s := range sections {
		fmt.Fprintf(b, "- [%s](#%s) (%d)\n", escape(s.title), s.anchor, len(s.routes))
	}
	b.WriteString("\n")
}

func writeRow(b *strings.Builder, r Route) {
	method := strings.Join(r.Methods, ", ")
	if method == "" {
		method = "(any)"
	}
	auth := r.Auth
	if auth == "" {
		auth = "**none**"
	}
	handler := r.Handler
	if handler == "" {
		handler = "(inline)"
	}
	capability := code(r.Cap)
	if r.Cap == "" && r.Authz != "" {
		capability = "_" + r.Authz + "_"
	}
	fmt.Fprintf(b, "| %s | `%s` | %s | %s | %s | `%s` | %s |\n",
		method,
		r.Path,
		auth,
		capability,
		escape(strings.Join(r.Gates, ", ")),
		handler,
		escape(r.Doc),
	)
}

func code(s string) string {
	if s == "" {
		return "-"
	}
	return "`" + s + "`"
}

func escape(s string) string {
	if s == "" {
		return "-"
	}
	return strings.ReplaceAll(s, "|", `\|`)
}
