// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: proto/node/node.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope for all messages over the stream.
type NodeMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServerUuid string                 `protobuf:"bytes,2,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_Auth
	//	*NodeMessage_AuthResult
	//	*NodeMessage_ListReq
	//	*NodeMessage_ListResp
	//	*NodeMessage_ReadReq
	//	*NodeMessage_WriteReq
	//	*NodeMessage_UploadReq
	//	*NodeMessage_SelectiveReadReq
	//	*NodeMessage_CreateReq
	//	*NodeMessage_DeleteReq
	//	*NodeMessage_RenameReq
	//	*NodeMessage_CopyReq
	//	*NodeMessage_Chunk
	//	*NodeMessage_TransferDone
	//	*NodeMessage_InspectOrphanReq
	//	*NodeMessage_InspectOrphanResp
	//	*NodeMessage_BackupListReq
	//	*NodeMessage_BackupListResp
	//	*NodeMessage_BackupOpenReq
	//	*NodeMessage_BackupDeleteReq
	//	*NodeMessage_BackupUsageReq
	//	*NodeMessage_BackupUsageResp
	//	*NodeMessage_RconExecReq
	//	*NodeMessage_RconExecResp
	//	*NodeMessage_Result
	//	*NodeMessage_Error
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_proto_node_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NodeMessage) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetAuth() *NodeAuth {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *NodeMessage) GetAuthResult() *AuthResult {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_AuthResult); ok {
			return x.AuthResult
		}
	}
	return nil
}

func (x *NodeMessage) GetListReq() *ListFilesReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ListReq); ok {
			return x.ListReq
		}
	}
	return nil
}

func (x *NodeMessage) GetListResp() *ListFilesResp {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ListResp); ok {
			return x.ListResp
		}
	}
	return nil
}

func (x *NodeMessage) GetReadReq() *ReadFileReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ReadReq); ok {
			return x.ReadReq
		}
	}
	return nil
}

func (x *NodeMessage) GetWriteReq() *WriteFileReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_WriteReq); ok {
			return x.WriteReq
		}
	}
	return nil
}

func (x *NodeMessage) GetUploadReq() *UploadFileReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_UploadReq); ok {
			return x.UploadReq
		}
	}
	return nil
}

func (x *NodeMessage) GetSelectiveReadReq() *SelectiveReadReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_SelectiveReadReq); ok {
			return x.SelectiveReadReq
		}
	}
	return nil
}

func (x *NodeMessage) GetCreateReq() *CreateFileReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_CreateReq); ok {
			return x.CreateReq
		}
	}
	return nil
}

func (x *NodeMessage) GetDeleteReq() *DeleteFileReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_DeleteReq); ok {
			return x.DeleteReq
		}
	}
	return nil
}

func (x *NodeMessage) GetRenameReq() *RenameFileReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_RenameReq); ok {
			return x.RenameReq
		}
	}
	return nil
}

func (x *NodeMessage) GetCopyReq() *CopyFileReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_CopyReq); ok {
			return x.CopyReq
		}
	}
	return nil
}

func (x *NodeMessage) GetChunk() *DataChunk {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *NodeMessage) GetTransferDone() *TransferDone {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_TransferDone); ok {
			return x.TransferDone
		}
	}
	return nil
}

func (x *NodeMessage) GetInspectOrphanReq() *InspectOrphanReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_InspectOrphanReq); ok {
			return x.InspectOrphanReq
		}
	}
	return nil
}

func (x *NodeMessage) GetInspectOrphanResp() *InspectOrphanResp {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_InspectOrphanResp); ok {
			return x.InspectOrphanResp
		}
	}
	return nil
}

func (x *NodeMessage) GetBackupListReq() *BackupListReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_BackupListReq); ok {
			return x.BackupListReq
		}
	}
	return nil
}

func (x *NodeMessage) GetBackupListResp() *BackupListResp {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_BackupListResp); ok {
			return x.BackupListResp
		}
	}
	return nil
}

func (x *NodeMessage) GetBackupOpenReq() *BackupOpenReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_BackupOpenReq); ok {
			return x.BackupOpenReq
		}
	}
	return nil
}

func (x *NodeMessage) GetBackupDeleteReq() *BackupDeleteReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_BackupDeleteReq); ok {
			return x.BackupDeleteReq
		}
	}
	return nil
}

func (x *NodeMessage) GetBackupUsageReq() *BackupUsageReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_BackupUsageReq); ok {
			return x.BackupUsageReq
		}
	}
	return nil
}

func (x *NodeMessage) GetBackupUsageResp() *BackupUsageResp {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_BackupUsageResp); ok {
			return x.BackupUsageResp
		}
	}
	return nil
}

func (x *NodeMessage) GetRconExecReq() *RconExecReq {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_RconExecReq); ok {
			return x.RconExecReq
		}
	}
	return nil
}

func (x *NodeMessage) GetRconExecResp() *RconExecResp {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_RconExecResp); ok {
			return x.RconExecResp
		}
	}
	return nil
}

func (x *NodeMessage) GetResult() *OpResult {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *NodeMessage) GetError() *OpError {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_Auth struct {
	// Auth (Node→Core, first message after Connect)
	Auth *NodeAuth `protobuf:"bytes,10,opt,name=auth,proto3,oneof"`
}

type NodeMessage_AuthResult struct {
	AuthResult *AuthResult `protobuf:"bytes,11,opt,name=auth_result,json=authResult,proto3,oneof"`
}

type NodeMessage_ListReq struct {
	// File Listing
	ListReq *ListFilesReq `protobuf:"bytes,20,opt,name=list_req,json=listReq,proto3,oneof"`
}

type NodeMessage_ListResp struct {
	ListResp *ListFilesResp `protobuf:"bytes,21,opt,name=list_resp,json=listResp,proto3,oneof"`
}

type NodeMessage_ReadReq struct {
	// File Read (Core→Node request, Node→Core chunks+done)
	ReadReq *ReadFileReq `protobuf:"bytes,30,opt,name=read_req,json=readReq,proto3,oneof"`
}

type NodeMessage_WriteReq struct {
	// File Write/Save (Core→Node request+chunks+done, Node→Core result)
	WriteReq *WriteFileReq `protobuf:"bytes,40,opt,name=write_req,json=writeReq,proto3,oneof"`
}

type NodeMessage_UploadReq struct {
	// File Upload (Core→Node: multipart data via chunks)
	UploadReq *UploadFileReq `protobuf:"bytes,45,opt,name=upload_req,json=uploadReq,proto3,oneof"`
}

type NodeMessage_SelectiveReadReq struct {
	// Selective Read (download selected files/folders as zip)
	SelectiveReadReq *SelectiveReadReq `protobuf:"bytes,31,opt,name=selective_read_req,json=selectiveReadReq,proto3,oneof"`
}

type NodeMessage_CreateReq struct {
	// File Create / Delete / Rename / Copy
	CreateReq *CreateFileReq `protobuf:"bytes,50,opt,name=create_req,json=createReq,proto3,oneof"`
}

type NodeMessage_DeleteReq struct {
	DeleteReq *DeleteFileReq `protobuf:"bytes,51,opt,name=delete_req,json=deleteReq,proto3,oneof"`
}

type NodeMessage_RenameReq struct {
	RenameReq *RenameFileReq `protobuf:"bytes,52,opt,name=rename_req,json=renameReq,proto3,oneof"`
}

type NodeMessage_CopyReq struct {
	CopyReq *CopyFileReq `protobuf:"bytes,53,opt,name=copy_req,json=copyReq,proto3,oneof"`
}

type NodeMessage_Chunk struct {
	// Chunked Data (bidirectional, 64KB per chunk)
	Chunk *DataChunk `protobuf:"bytes,60,opt,name=chunk,proto3,oneof"`
}

type NodeMessage_TransferDone struct {
	TransferDone *TransferDone `protobuf:"bytes,61,opt,name=transfer_done,json=transferDone,proto3,oneof"`
}

type NodeMessage_InspectOrphanReq struct {
	// Orphan inspection (Core→Node request, Node→Core response)
	InspectOrphanReq *InspectOrphanReq `protobuf:"bytes,92,opt,name=inspect_orphan_req,json=inspectOrphanReq,proto3,oneof"`
}

type NodeMessage_InspectOrphanResp struct {
	InspectOrphanResp *InspectOrphanResp `protobuf:"bytes,93,opt,name=inspect_orphan_resp,json=inspectOrphanResp,proto3,oneof"`
}

type NodeMessage_BackupListReq struct {
	// Node-local backup ops (server_uuid is carried in NodeMessage.server_uuid).
	// Used when backup.mode == "node-local" — the .tar.gz archives live inside
	// each server's <server-dir>/.dylaris-backups/ folder on the Node's disk.
	BackupListReq *BackupListReq `protobuf:"bytes,100,opt,name=backup_list_req,json=backupListReq,proto3,oneof"`
}

type NodeMessage_BackupListResp struct {
	BackupListResp *BackupListResp `protobuf:"bytes,101,opt,name=backup_list_resp,json=backupListResp,proto3,oneof"`
}

type NodeMessage_BackupOpenReq struct {
	BackupOpenReq *BackupOpenReq `protobuf:"bytes,102,opt,name=backup_open_req,json=backupOpenReq,proto3,oneof"` // streaming read of one archive
}

type NodeMessage_BackupDeleteReq struct {
	BackupDeleteReq *BackupDeleteReq `protobuf:"bytes,103,opt,name=backup_delete_req,json=backupDeleteReq,proto3,oneof"`
}

type NodeMessage_BackupUsageReq struct {
	BackupUsageReq *BackupUsageReq `protobuf:"bytes,104,opt,name=backup_usage_req,json=backupUsageReq,proto3,oneof"`
}

type NodeMessage_BackupUsageResp struct {
	BackupUsageResp *BackupUsageResp `protobuf:"bytes,105,opt,name=backup_usage_resp,json=backupUsageResp,proto3,oneof"`
}

type NodeMessage_RconExecReq struct {
	// RCON exec (Phase 9): Core→Node request, Node→Core response.
	// server_uuid in NodeMessage.server_uuid identifies which container.
	// Node opens TCP to the container's mapped RCON port, auths with the
	// stored password, sends the command, returns whatever the server
	// wrote back. One request per command — no streaming.
	RconExecReq *RconExecReq `protobuf:"bytes,110,opt,name=rcon_exec_req,json=rconExecReq,proto3,oneof"`
}

type NodeMessage_RconExecResp struct {
	RconExecResp *RconExecResp `protobuf:"bytes,111,opt,name=rcon_exec_resp,json=rconExecResp,proto3,oneof"`
}

type NodeMessage_Result struct {
	// Generic result / error
	Result *OpResult `protobuf:"bytes,90,opt,name=result,proto3,oneof"`
}

type NodeMessage_Error struct {
	Error *OpError `protobuf:"bytes,91,opt,name=error,proto3,oneof"`
}

func (*NodeMessage_Auth) isNodeMessage_Payload() {}

func (*NodeMessage_AuthResult) isNodeMessage_Payload() {}

func (*NodeMessage_ListReq) isNodeMessage_Payload() {}

func (*NodeMessage_ListResp) isNodeMessage_Payload() {}

func (*NodeMessage_ReadReq) isNodeMessage_Payload() {}

func (*NodeMessage_WriteReq) isNodeMessage_Payload() {}

func (*NodeMessage_UploadReq) isNodeMessage_Payload() {}

func (*NodeMessage_SelectiveReadReq) isNodeMessage_Payload() {}

func (*NodeMessage_CreateReq) isNodeMessage_Payload() {}

func (*NodeMessage_DeleteReq) isNodeMessage_Payload() {}

func (*NodeMessage_RenameReq) isNodeMessage_Payload() {}

func (*NodeMessage_CopyReq) isNodeMessage_Payload() {}

func (*NodeMessage_Chunk) isNodeMessage_Payload() {}

func (*NodeMessage_TransferDone) isNodeMessage_Payload() {}

func (*NodeMessage_InspectOrphanReq) isNodeMessage_Payload() {}

func (*NodeMessage_InspectOrphanResp) isNodeMessage_Payload() {}

func (*NodeMessage_BackupListReq) isNodeMessage_Payload() {}

func (*NodeMessage_BackupListResp) isNodeMessage_Payload() {}

func (*NodeMessage_BackupOpenReq) isNodeMessage_Payload() {}

func (*NodeMessage_BackupDeleteReq) isNodeMessage_Payload() {}

func (*NodeMessage_BackupUsageReq) isNodeMessage_Payload() {}

func (*NodeMessage_BackupUsageResp) isNodeMessage_Payload() {}

func (*NodeMessage_RconExecReq) isNodeMessage_Payload() {}

func (*NodeMessage_RconExecResp) isNodeMessage_Payload() {}

func (*NodeMessage_Result) isNodeMessage_Payload() {}

func (*NodeMessage_Error) isNodeMessage_Payload() {}

// ─── Auth ────────────────────────────────────────────────────────────
type NodeAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeToken     string                 `protobuf:"bytes,1,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	Ips           *NodeIPs               `protobuf:"bytes,2,opt,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAuth) Reset() {
	*x = NodeAuth{}
	mi := &file_proto_node_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAuth) ProtoMessage() {}

func (x *NodeAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAuth.ProtoReflect.Descriptor instead.
func (*NodeAuth) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeAuth) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *NodeAuth) GetIps() *NodeIPs {
	if x != nil {
		return x.Ips
	}
	return nil
}

type AuthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CoreId        string                 `protobuf:"bytes,2,opt,name=core_id,json=coreId,proto3" json:"core_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_proto_node_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResult) GetCoreId() string {
	if x != nil {
		return x.CoreId
	}
	return ""
}

func (x *AuthResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeIPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        string                 `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private       []string               `protobuf:"bytes,2,rep,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIPs) Reset() {
	*x = NodeIPs{}
	mi := &file_proto_node_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIPs) ProtoMessage() {}

func (x *NodeIPs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIPs.ProtoReflect.Descriptor instead.
func (*NodeIPs) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{3}
}

func (x *NodeIPs) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *NodeIPs) GetPrivate() []string {
	if x != nil {
		return x.Private
	}
	return nil
}

// ─── File Operations ─────────────────────────────────────────────────
type ListFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesReq) Reset() {
	*x = ListFilesReq{}
	mi := &file_proto_node_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesReq) ProtoMessage() {}

func (x *ListFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesReq.ProtoReflect.Descriptor instead.
func (*ListFilesReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResp) Reset() {
	*x = ListFilesResp{}
	mi := &file_proto_node_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResp) ProtoMessage() {}

func (x *ListFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResp.ProtoReflect.Descriptor instead.
func (*ListFilesResp) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesResp) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_node_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{6}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ZipIfDir      bool                   `protobuf:"varint,2,opt,name=zip_if_dir,json=zipIfDir,proto3" json:"zip_if_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileReq) Reset() {
	*x = ReadFileReq{}
	mi := &file_proto_node_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileReq) ProtoMessage() {}

func (x *ReadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileReq.ProtoReflect.Descriptor instead.
func (*ReadFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileReq) GetZipIfDir() bool {
	if x != nil {
		return x.ZipIfDir
	}
	return false
}

// Selective download: zip only selected paths within a base directory.
// Reusable for backups (same selection mechanism).
type SelectiveReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasePath      string                 `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`     // e.g. "" (server root) or "plugins/"
	Selected      []string               `protobuf:"bytes,2,rep,name=selected,proto3" json:"selected,omitempty"`                     // e.g. ["WorldEdit/", "config.yml"]
	SelectAll     bool                   `protobuf:"varint,3,opt,name=select_all,json=selectAll,proto3" json:"select_all,omitempty"` // if true, ignore selected list and zip everything
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectiveReadReq) Reset() {
	*x = SelectiveReadReq{}
	mi := &file_proto_node_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectiveReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectiveReadReq) ProtoMessage() {}

func (x *SelectiveReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectiveReadReq.ProtoReflect.Descriptor instead.
func (*SelectiveReadReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{8}
}

func (x *SelectiveReadReq) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *SelectiveReadReq) GetSelected() []string {
	if x != nil {
		return x.Selected
	}
	return nil
}

func (x *SelectiveReadReq) GetSelectAll() bool {
	if x != nil {
		return x.SelectAll
	}
	return false
}

type WriteFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileReq) Reset() {
	*x = WriteFileReq{}
	mi := &file_proto_node_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileReq) ProtoMessage() {}

func (x *WriteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileReq.ProtoReflect.Descriptor instead.
func (*WriteFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{9}
}

func (x *WriteFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileReq) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type UploadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Strategy      string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`                                // "replace", "merge", etc.
	MergeConflict string                 `protobuf:"bytes,5,opt,name=merge_conflict,json=mergeConflict,proto3" json:"merge_conflict,omitempty"` // "replace", "ignore"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileReq) Reset() {
	*x = UploadFileReq{}
	mi := &file_proto_node_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileReq) ProtoMessage() {}

func (x *UploadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileReq.ProtoReflect.Descriptor instead.
func (*UploadFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadFileReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileReq) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadFileReq) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *UploadFileReq) GetMergeConflict() string {
	if x != nil {
		return x.MergeConflict
	}
	return ""
}

type CreateFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileReq) Reset() {
	*x = CreateFileReq{}
	mi := &file_proto_node_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileReq) ProtoMessage() {}

func (x *CreateFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileReq.ProtoReflect.Descriptor instead.
func (*CreateFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{11}
}

func (x *CreateFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileReq) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type DeleteFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileReq) Reset() {
	*x = DeleteFileReq{}
	mi := &file_proto_node_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReq) ProtoMessage() {}

func (x *DeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReq.ProtoReflect.Descriptor instead.
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RenameFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileReq) Reset() {
	*x = RenameFileReq{}
	mi := &file_proto_node_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileReq) ProtoMessage() {}

func (x *RenameFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileReq.ProtoReflect.Descriptor instead.
func (*RenameFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{13}
}

func (x *RenameFileReq) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameFileReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type CopyFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPath       string                 `protobuf:"bytes,1,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	DstPath       string                 `protobuf:"bytes,2,opt,name=dst_path,json=dstPath,proto3" json:"dst_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileReq) Reset() {
	*x = CopyFileReq{}
	mi := &file_proto_node_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileReq) ProtoMessage() {}

func (x *CopyFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileReq.ProtoReflect.Descriptor instead.
func (*CopyFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{14}
}

func (x *CopyFileReq) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *CopyFileReq) GetDstPath() string {
	if x != nil {
		return x.DstPath
	}
	return ""
}

// ─── Chunked Transfer ────────────────────────────────────────────────
type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // max 64KB
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_proto_node_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{15}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type TransferDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // Optional: filename for downloads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferDone) Reset() {
	*x = TransferDone{}
	mi := &file_proto_node_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferDone) ProtoMessage() {}

func (x *TransferDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferDone.ProtoReflect.Descriptor instead.
func (*TransferDone) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{16}
}

func (x *TransferDone) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TransferDone) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// ─── Orphan Inspection ───────────────────────────────────────────────
// Read-only: returns .dylaris.json metadata, .active_server content, and
// a directory scan of sub-servers. No mutation is performed.
type InspectOrphanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectOrphanReq) Reset() {
	*x = InspectOrphanReq{}
	mi := &file_proto_node_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectOrphanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectOrphanReq) ProtoMessage() {}

func (x *InspectOrphanReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectOrphanReq.ProtoReflect.Descriptor instead.
func (*InspectOrphanReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{17}
}

type SubServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubServerInfo) Reset() {
	*x = SubServerInfo{}
	mi := &file_proto_node_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubServerInfo) ProtoMessage() {}

func (x *SubServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubServerInfo.ProtoReflect.Descriptor instead.
func (*SubServerInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{18}
}

func (x *SubServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubServerInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type InspectOrphanResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasMetadata     bool                   `protobuf:"varint,1,opt,name=has_metadata,json=hasMetadata,proto3" json:"has_metadata,omitempty"`              // false → .dylaris.json absent or unparseable
	MetadataJson    string                 `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`            // raw JSON of .dylaris.json (only when has_metadata=true)
	ActiveSubServer string                 `protobuf:"bytes,3,opt,name=active_sub_server,json=activeSubServer,proto3" json:"active_sub_server,omitempty"` // content of .active_server, or "" if absent
	SubServers      []*SubServerInfo       `protobuf:"bytes,4,rep,name=sub_servers,json=subServers,proto3" json:"sub_servers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InspectOrphanResp) Reset() {
	*x = InspectOrphanResp{}
	mi := &file_proto_node_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectOrphanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectOrphanResp) ProtoMessage() {}

func (x *InspectOrphanResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectOrphanResp.ProtoReflect.Descriptor instead.
func (*InspectOrphanResp) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{19}
}

func (x *InspectOrphanResp) GetHasMetadata() bool {
	if x != nil {
		return x.HasMetadata
	}
	return false
}

func (x *InspectOrphanResp) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *InspectOrphanResp) GetActiveSubServer() string {
	if x != nil {
		return x.ActiveSubServer
	}
	return ""
}

func (x *InspectOrphanResp) GetSubServers() []*SubServerInfo {
	if x != nil {
		return x.SubServers
	}
	return nil
}

// ─── Node-local backups ──────────────────────────────────────────────
type BackupListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupListReq) Reset() {
	*x = BackupListReq{}
	mi := &file_proto_node_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupListReq) ProtoMessage() {}

func (x *BackupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupListReq.ProtoReflect.Descriptor instead.
func (*BackupListReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{20}
}

type BackupObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // archive filename (e.g. "20260524-141200.tar.gz")
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedUnix  int64                  `protobuf:"varint,3,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupObject) Reset() {
	*x = BackupObject{}
	mi := &file_proto_node_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupObject) ProtoMessage() {}

func (x *BackupObject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupObject.ProtoReflect.Descriptor instead.
func (*BackupObject) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{21}
}

func (x *BackupObject) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BackupObject) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BackupObject) GetModifiedUnix() int64 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

type BackupListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*BackupObject        `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupListResp) Reset() {
	*x = BackupListResp{}
	mi := &file_proto_node_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupListResp) ProtoMessage() {}

func (x *BackupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupListResp.ProtoReflect.Descriptor instead.
func (*BackupListResp) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{22}
}

func (x *BackupListResp) GetObjects() []*BackupObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type BackupOpenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // filename within .dylaris-backups/
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupOpenReq) Reset() {
	*x = BackupOpenReq{}
	mi := &file_proto_node_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupOpenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupOpenReq) ProtoMessage() {}

func (x *BackupOpenReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupOpenReq.ProtoReflect.Descriptor instead.
func (*BackupOpenReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{23}
}

func (x *BackupOpenReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type BackupDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupDeleteReq) Reset() {
	*x = BackupDeleteReq{}
	mi := &file_proto_node_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDeleteReq) ProtoMessage() {}

func (x *BackupDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDeleteReq.ProtoReflect.Descriptor instead.
func (*BackupDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{24}
}

func (x *BackupDeleteReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type BackupUsageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupUsageReq) Reset() {
	*x = BackupUsageReq{}
	mi := &file_proto_node_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupUsageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupUsageReq) ProtoMessage() {}

func (x *BackupUsageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupUsageReq.ProtoReflect.Descriptor instead.
func (*BackupUsageReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{25}
}

type BackupUsageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     int64                  `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupUsageResp) Reset() {
	*x = BackupUsageResp{}
	mi := &file_proto_node_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupUsageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupUsageResp) ProtoMessage() {}

func (x *BackupUsageResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupUsageResp.ProtoReflect.Descriptor instead.
func (*BackupUsageResp) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{26}
}

func (x *BackupUsageResp) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *BackupUsageResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ─── Results ─────────────────────────────────────────────────────────
type OpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResult) Reset() {
	*x = OpResult{}
	mi := &file_proto_node_node_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResult) ProtoMessage() {}

func (x *OpResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResult.ProtoReflect.Descriptor instead.
func (*OpResult) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{27}
}

func (x *OpResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OpError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpError) Reset() {
	*x = OpError{}
	mi := &file_proto_node_node_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpError) ProtoMessage() {}

func (x *OpError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpError.ProtoReflect.Descriptor instead.
func (*OpError) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{28}
}

func (x *OpError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OpError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─── RCON (Phase 9) ──────────────────────────────────────────────────
// Node owns the container, knows its mapped RCON host:port (or container
// name on the dylaris_net overlay) and the rcon_password the Core passes
// here. Stateless per call — no connection pooling V1.
type RconExecReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	RconPassword  string                 `protobuf:"bytes,2,opt,name=rcon_password,json=rconPassword,proto3" json:"rcon_password,omitempty"`
	RconPort      int32                  `protobuf:"varint,3,opt,name=rcon_port,json=rconPort,proto3" json:"rcon_port,omitempty"`    // 0 → use container's mapped 25575
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // 0 → defaults to 3000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconExecReq) Reset() {
	*x = RconExecReq{}
	mi := &file_proto_node_node_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconExecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconExecReq) ProtoMessage() {}

func (x *RconExecReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconExecReq.ProtoReflect.Descriptor instead.
func (*RconExecReq) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{29}
}

func (x *RconExecReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RconExecReq) GetRconPassword() string {
	if x != nil {
		return x.RconPassword
	}
	return ""
}

func (x *RconExecReq) GetRconPort() int32 {
	if x != nil {
		return x.RconPort
	}
	return 0
}

func (x *RconExecReq) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type RconExecResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconExecResp) Reset() {
	*x = RconExecResp{}
	mi := &file_proto_node_node_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconExecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconExecResp) ProtoMessage() {}

func (x *RconExecResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconExecResp.ProtoReflect.Descriptor instead.
func (*RconExecResp) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{30}
}

func (x *RconExecResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RconExecResp) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RconExecResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RconExecResp) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_node_node_proto protoreflect.FileDescriptor

const file_proto_node_node_proto_rawDesc = "" +
	"\n" +
	"\x15proto/node/node.proto\x12\fdylaris.node\"\xe4\r\n" +
	"\vNodeMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vserver_uuid\x18\x02 \x01(\tR\n" +
	"serverUuid\x12,\n" +
	"\x04auth\x18\n" +
	" \x01(\v2\x16.dylaris.node.NodeAuthH\x00R\x04auth\x12;\n" +
	"\vauth_result\x18\v \x01(\v2\x18.dylaris.node.AuthResultH\x00R\n" +
	"authResult\x127\n" +
	"\blist_req\x18\x14 \x01(\v2\x1a.dylaris.node.ListFilesReqH\x00R\alistReq\x12:\n" +
	"\tlist_resp\x18\x15 \x01(\v2\x1b.dylaris.node.ListFilesRespH\x00R\blistResp\x126\n" +
	"\bread_req\x18\x1e \x01(\v2\x19.dylaris.node.ReadFileReqH\x00R\areadReq\x129\n" +
	"\twrite_req\x18( \x01(\v2\x1a.dylaris.node.WriteFileReqH\x00R\bwriteReq\x12<\n" +
	"\n" +
	"upload_req\x18- \x01(\v2\x1b.dylaris.node.UploadFileReqH\x00R\tuploadReq\x12N\n" +
	"\x12selective_read_req\x18\x1f \x01(\v2\x1e.dylaris.node.SelectiveReadReqH\x00R\x10selectiveReadReq\x12<\n" +
	"\n" +
	"create_req\x182 \x01(\v2\x1b.dylaris.node.CreateFileReqH\x00R\tcreateReq\x12<\n" +
	"\n" +
	"delete_req\x183 \x01(\v2\x1b.dylaris.node.DeleteFileReqH\x00R\tdeleteReq\x12<\n" +
	"\n" +
	"rename_req\x184 \x01(\v2\x1b.dylaris.node.RenameFileReqH\x00R\trenameReq\x126\n" +
	"\bcopy_req\x185 \x01(\v2\x19.dylaris.node.CopyFileReqH\x00R\acopyReq\x12/\n" +
	"\x05chunk\x18< \x01(\v2\x17.dylaris.node.DataChunkH\x00R\x05chunk\x12A\n" +
	"\rtransfer_done\x18= \x01(\v2\x1a.dylaris.node.TransferDoneH\x00R\ftransferDone\x12N\n" +
	"\x12inspect_orphan_req\x18\\ \x01(\v2\x1e.dylaris.node.InspectOrphanReqH\x00R\x10inspectOrphanReq\x12Q\n" +
	"\x13inspect_orphan_resp\x18] \x01(\v2\x1f.dylaris.node.InspectOrphanRespH\x00R\x11inspectOrphanResp\x12E\n" +
	"\x0fbackup_list_req\x18d \x01(\v2\x1b.dylaris.node.BackupListReqH\x00R\rbackupListReq\x12H\n" +
	"\x10backup_list_resp\x18e \x01(\v2\x1c.dylaris.node.BackupListRespH\x00R\x0ebackupListResp\x12E\n" +
	"\x0fbackup_open_req\x18f \x01(\v2\x1b.dylaris.node.BackupOpenReqH\x00R\rbackupOpenReq\x12K\n" +
	"\x11backup_delete_req\x18g \x01(\v2\x1d.dylaris.node.BackupDeleteReqH\x00R\x0fbackupDeleteReq\x12H\n" +
	"\x10backup_usage_req\x18h \x01(\v2\x1c.dylaris.node.BackupUsageReqH\x00R\x0ebackupUsageReq\x12K\n" +
	"\x11backup_usage_resp\x18i \x01(\v2\x1d.dylaris.node.BackupUsageRespH\x00R\x0fbackupUsageResp\x12?\n" +
	"\rrcon_exec_req\x18n \x01(\v2\x19.dylaris.node.RconExecReqH\x00R\vrconExecReq\x12B\n" +
	"\x0ercon_exec_resp\x18o \x01(\v2\x1a.dylaris.node.RconExecRespH\x00R\frconExecResp\x120\n" +
	"\x06result\x18Z \x01(\v2\x16.dylaris.node.OpResultH\x00R\x06result\x12-\n" +
	"\x05error\x18[ \x01(\v2\x15.dylaris.node.OpErrorH\x00R\x05errorB\t\n" +
	"\apayload\"R\n" +
	"\bNodeAuth\x12\x1d\n" +
	"\n" +
	"node_token\x18\x01 \x01(\tR\tnodeToken\x12'\n" +
	"\x03ips\x18\x02 \x01(\v2\x15.dylaris.node.NodeIPsR\x03ips\"O\n" +
	"\n" +
	"AuthResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\acore_id\x18\x02 \x01(\tR\x06coreId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\";\n" +
	"\aNodeIPs\x12\x16\n" +
	"\x06public\x18\x01 \x01(\tR\x06public\x12\x18\n" +
	"\aprivate\x18\x02 \x03(\tR\aprivate\"\"\n" +
	"\fListFilesReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"=\n" +
	"\rListFilesResp\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.dylaris.node.FileInfoR\x05files\"I\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"?\n" +
	"\vReadFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\n" +
	"zip_if_dir\x18\x02 \x01(\bR\bzipIfDir\"j\n" +
	"\x10SelectiveReadReq\x12\x1b\n" +
	"\tbase_path\x18\x01 \x01(\tR\bbasePath\x12\x1a\n" +
	"\bselected\x18\x02 \x03(\tR\bselected\x12\x1d\n" +
	"\n" +
	"select_all\x18\x03 \x01(\bR\tselectAll\"A\n" +
	"\fWriteFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\"\xa1\x01\n" +
	"\rUploadFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\x12%\n" +
	"\x0emerge_conflict\x18\x05 \x01(\tR\rmergeConflict\":\n" +
	"\rCreateFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\"#\n" +
	"\rDeleteFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"E\n" +
	"\rRenameFileReq\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"C\n" +
	"\vCopyFileReq\x12\x19\n" +
	"\bsrc_path\x18\x01 \x01(\tR\asrcPath\x12\x19\n" +
	"\bdst_path\x18\x02 \x01(\tR\adstPath\"7\n" +
	"\tDataChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"K\n" +
	"\fTransferDone\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\x12\n" +
	"\x10InspectOrphanReq\"7\n" +
	"\rSubServerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xc5\x01\n" +
	"\x11InspectOrphanResp\x12!\n" +
	"\fhas_metadata\x18\x01 \x01(\bR\vhasMetadata\x12#\n" +
	"\rmetadata_json\x18\x02 \x01(\tR\fmetadataJson\x12*\n" +
	"\x11active_sub_server\x18\x03 \x01(\tR\x0factiveSubServer\x12<\n" +
	"\vsub_servers\x18\x04 \x03(\v2\x1b.dylaris.node.SubServerInfoR\n" +
	"subServers\"\x0f\n" +
	"\rBackupListReq\"Y\n" +
	"\fBackupObject\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12#\n" +
	"\rmodified_unix\x18\x03 \x01(\x03R\fmodifiedUnix\"F\n" +
	"\x0eBackupListResp\x124\n" +
	"\aobjects\x18\x01 \x03(\v2\x1a.dylaris.node.BackupObjectR\aobjects\"!\n" +
	"\rBackupOpenReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"#\n" +
	"\x0fBackupDeleteReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x10\n" +
	"\x0eBackupUsageReq\"F\n" +
	"\x0fBackupUsageResp\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x03R\tusedBytes\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"$\n" +
	"\bOpResult\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\aOpError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x01\n" +
	"\vRconExecReq\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12#\n" +
	"\rrcon_password\x18\x02 \x01(\tR\frconPassword\x12\x1b\n" +
	"\trcon_port\x18\x03 \x01(\x05R\brconPort\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"m\n" +
	"\fRconExecResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs2V\n" +
	"\vNodeService\x12G\n" +
	"\vNodeConnect\x12\x19.dylaris.node.NodeMessage\x1a\x19.dylaris.node.NodeMessage(\x010\x01B\x14Z\x12dylaris-proto/nodeb\x06proto3"

var (
	file_proto_node_node_proto_rawDescOnce sync.Once
	file_proto_node_node_proto_rawDescData []byte
)

func file_proto_node_node_proto_rawDescGZIP() []byte {
	file_proto_node_node_proto_rawDescOnce.Do(func() {
		file_proto_node_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_node_proto_rawDesc), len(file_proto_node_node_proto_rawDesc)))
	})
	return file_proto_node_node_proto_rawDescData
}

var file_proto_node_node_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_node_node_proto_goTypes = []any{
	(*NodeMessage)(nil),       // 0: dylaris.node.NodeMessage
	(*NodeAuth)(nil),          // 1: dylaris.node.NodeAuth
	(*AuthResult)(nil),        // 2: dylaris.node.AuthResult
	(*NodeIPs)(nil),           // 3: dylaris.node.NodeIPs
	(*ListFilesReq)(nil),      // 4: dylaris.node.ListFilesReq
	(*ListFilesResp)(nil),     // 5: dylaris.node.ListFilesResp
	(*FileInfo)(nil),          // 6: dylaris.node.FileInfo
	(*ReadFileReq)(nil),       // 7: dylaris.node.ReadFileReq
	(*SelectiveReadReq)(nil),  // 8: dylaris.node.SelectiveReadReq
	(*WriteFileReq)(nil),      // 9: dylaris.node.WriteFileReq
	(*UploadFileReq)(nil),     // 10: dylaris.node.UploadFileReq
	(*CreateFileReq)(nil),     // 11: dylaris.node.CreateFileReq
	(*DeleteFileReq)(nil),     // 12: dylaris.node.DeleteFileReq
	(*RenameFileReq)(nil),     // 13: dylaris.node.RenameFileReq
	(*CopyFileReq)(nil),       // 14: dylaris.node.CopyFileReq
	(*DataChunk)(nil),         // 15: dylaris.node.DataChunk
	(*TransferDone)(nil),      // 16: dylaris.node.TransferDone
	(*InspectOrphanReq)(nil),  // 17: dylaris.node.InspectOrphanReq
	(*SubServerInfo)(nil),     // 18: dylaris.node.SubServerInfo
	(*InspectOrphanResp)(nil), // 19: dylaris.node.InspectOrphanResp
	(*BackupListReq)(nil),     // 20: dylaris.node.BackupListReq
	(*BackupObject)(nil),      // 21: dylaris.node.BackupObject
	(*BackupListResp)(nil),    // 22: dylaris.node.BackupListResp
	(*BackupOpenReq)(nil),     // 23: dylaris.node.BackupOpenReq
	(*BackupDeleteReq)(nil),   // 24: dylaris.node.BackupDeleteReq
	(*BackupUsageReq)(nil),    // 25: dylaris.node.BackupUsageReq
	(*BackupUsageResp)(nil),   // 26: dylaris.node.BackupUsageResp
	(*OpResult)(nil),          // 27: dylaris.node.OpResult
	(*OpError)(nil),           // 28: dylaris.node.OpError
	(*RconExecReq)(nil),       // 29: dylaris.node.RconExecReq
	(*RconExecResp)(nil),      // 30: dylaris.node.RconExecResp
}
var file_proto_node_node_proto_depIdxs = []int32{
	1,  // 0: dylaris.node.NodeMessage.auth:type_name -> dylaris.node.NodeAuth
	2,  // 1: dylaris.node.NodeMessage.auth_result:type_name -> dylaris.node.AuthResult
	4,  // 2: dylaris.node.NodeMessage.list_req:type_name -> dylaris.node.ListFilesReq
	5,  // 3: dylaris.node.NodeMessage.list_resp:type_name -> dylaris.node.ListFilesResp
	7,  // 4: dylaris.node.NodeMessage.read_req:type_name -> dylaris.node.ReadFileReq
	9,  // 5: dylaris.node.NodeMessage.write_req:type_name -> dylaris.node.WriteFileReq
	10, // 6: dylaris.node.NodeMessage.upload_req:type_name -> dylaris.node.UploadFileReq
	8,  // 7: dylaris.node.NodeMessage.selective_read_req:type_name -> dylaris.node.SelectiveReadReq
	11, // 8: dylaris.node.NodeMessage.create_req:type_name -> dylaris.node.CreateFileReq
	12, // 9: dylaris.node.NodeMessage.delete_req:type_name -> dylaris.node.DeleteFileReq
	13, // 10: dylaris.node.NodeMessage.rename_req:type_name -> dylaris.node.RenameFileReq
	14, // 11: dylaris.node.NodeMessage.copy_req:type_name -> dylaris.node.CopyFileReq
	15, // 12: dylaris.node.NodeMessage.chunk:type_name -> dylaris.node.DataChunk
	16, // 13: dylaris.node.NodeMessage.transfer_done:type_name -> dylaris.node.TransferDone
	17, // 14: dylaris.node.NodeMessage.inspect_orphan_req:type_name -> dylaris.node.InspectOrphanReq
	19, // 15: dylaris.node.NodeMessage.inspect_orphan_resp:type_name -> dylaris.node.InspectOrphanResp
	20, // 16: dylaris.node.NodeMessage.backup_list_req:type_name -> dylaris.node.BackupListReq
	22, // 17: dylaris.node.NodeMessage.backup_list_resp:type_name -> dylaris.node.BackupListResp
	23, // 18: dylaris.node.NodeMessage.backup_open_req:type_name -> dylaris.node.BackupOpenReq
	24, // 19: dylaris.node.NodeMessage.backup_delete_req:type_name -> dylaris.node.BackupDeleteReq
	25, // 20: dylaris.node.NodeMessage.backup_usage_req:type_name -> dylaris.node.BackupUsageReq
	26, // 21: dylaris.node.NodeMessage.backup_usage_resp:type_name -> dylaris.node.BackupUsageResp
	29, // 22: dylaris.node.NodeMessage.rcon_exec_req:type_name -> dylaris.node.RconExecReq
	30, // 23: dylaris.node.NodeMessage.rcon_exec_resp:type_name -> dylaris.node.RconExecResp
	27, // 24: dylaris.node.NodeMessage.result:type_name -> dylaris.node.OpResult
	28, // 25: dylaris.node.NodeMessage.error:type_name -> dylaris.node.OpError
	3,  // 26: dylaris.node.NodeAuth.ips:type_name -> dylaris.node.NodeIPs
	6,  // 27: dylaris.node.ListFilesResp.files:type_name -> dylaris.node.FileInfo
	18, // 28: dylaris.node.InspectOrphanResp.sub_servers:type_name -> dylaris.node.SubServerInfo
	21, // 29: dylaris.node.BackupListResp.objects:type_name -> dylaris.node.BackupObject
	0,  // 30: dylaris.node.NodeService.NodeConnect:input_type -> dylaris.node.NodeMessage
	0,  // 31: dylaris.node.NodeService.NodeConnect:output_type -> dylaris.node.NodeMessage
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_node_node_proto_init() }
func file_proto_node_node_proto_init() {
	if File_proto_node_node_proto != nil {
		return
	}
	file_proto_node_node_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeMessage_Auth)(nil),
		(*NodeMessage_AuthResult)(nil),
		(*NodeMessage_ListReq)(nil),
		(*NodeMessage_ListResp)(nil),
		(*NodeMessage_ReadReq)(nil),
		(*NodeMessage_WriteReq)(nil),
		(*NodeMessage_UploadReq)(nil),
		(*NodeMessage_SelectiveReadReq)(nil),
		(*NodeMessage_CreateReq)(nil),
		(*NodeMessage_DeleteReq)(nil),
		(*NodeMessage_RenameReq)(nil),
		(*NodeMessage_CopyReq)(nil),
		(*NodeMessage_Chunk)(nil),
		(*NodeMessage_TransferDone)(nil),
		(*NodeMessage_InspectOrphanReq)(nil),
		(*NodeMessage_InspectOrphanResp)(nil),
		(*NodeMessage_BackupListReq)(nil),
		(*NodeMessage_BackupListResp)(nil),
		(*NodeMessage_BackupOpenReq)(nil),
		(*NodeMessage_BackupDeleteReq)(nil),
		(*NodeMessage_BackupUsageReq)(nil),
		(*NodeMessage_BackupUsageResp)(nil),
		(*NodeMessage_RconExecReq)(nil),
		(*NodeMessage_RconExecResp)(nil),
		(*NodeMessage_Result)(nil),
		(*NodeMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_node_proto_rawDesc), len(file_proto_node_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_node_proto_goTypes,
		DependencyIndexes: file_proto_node_node_proto_depIdxs,
		MessageInfos:      file_proto_node_node_proto_msgTypes,
	}.Build()
	File_proto_node_node_proto = out.File
	file_proto_node_node_proto_goTypes = nil
	file_proto_node_node_proto_depIdxs = nil
}
